# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ODMRGuiUI.ui'
#
# Created: Wed Jun 17 19:11:45 2015
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1063, 696)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 5, 12, 1, 1)
        self.odmr_cb_min_InputWidget = QtGui.QSpinBox(self.centralwidget)
        self.odmr_cb_min_InputWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.odmr_cb_min_InputWidget.setMaximum(999999999)
        self.odmr_cb_min_InputWidget.setProperty("value", 100)
        self.odmr_cb_min_InputWidget.setObjectName(_fromUtf8("odmr_cb_min_InputWidget"))
        self.gridLayout.addWidget(self.odmr_cb_min_InputWidget, 9, 12, 1, 2)
        self.odmr_cb_max_InputWidget = QtGui.QSpinBox(self.centralwidget)
        self.odmr_cb_max_InputWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.odmr_cb_max_InputWidget.setMinimum(0)
        self.odmr_cb_max_InputWidget.setMaximum(999999999)
        self.odmr_cb_max_InputWidget.setProperty("value", 100000)
        self.odmr_cb_max_InputWidget.setObjectName(_fromUtf8("odmr_cb_max_InputWidget"))
        self.gridLayout.addWidget(self.odmr_cb_max_InputWidget, 4, 12, 1, 2)
        self.odmr_cb_ViewWidget = PlotWidget(self.centralwidget)
        self.odmr_cb_ViewWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.odmr_cb_ViewWidget.setObjectName(_fromUtf8("odmr_cb_ViewWidget"))
        self.gridLayout.addWidget(self.odmr_cb_ViewWidget, 6, 12, 2, 2)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 8, 12, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 4, 1, 2)
        self.step_freq_InputWidget = QtGui.QLineEdit(self.centralwidget)
        self.step_freq_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.step_freq_InputWidget.setObjectName(_fromUtf8("step_freq_InputWidget"))
        self.gridLayout.addWidget(self.step_freq_InputWidget, 1, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 5, 1, 1)
        self.mode_ComboWidget = QtGui.QComboBox(self.centralwidget)
        self.mode_ComboWidget.setObjectName(_fromUtf8("mode_ComboWidget"))
        self.gridLayout.addWidget(self.mode_ComboWidget, 0, 6, 1, 1)
        self.stop_freq_InputWidget = QtGui.QLineEdit(self.centralwidget)
        self.stop_freq_InputWidget.setMaximumSize(QtCore.QSize(75, 16777215))
        self.stop_freq_InputWidget.setObjectName(_fromUtf8("stop_freq_InputWidget"))
        self.gridLayout.addWidget(self.stop_freq_InputWidget, 1, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.runtime_InputWidget = QtGui.QLineEdit(self.centralwidget)
        self.runtime_InputWidget.setEnabled(True)
        self.runtime_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.runtime_InputWidget.setObjectName(_fromUtf8("runtime_InputWidget"))
        self.gridLayout.addWidget(self.runtime_InputWidget, 3, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.frequency_InputWidget = QtGui.QLineEdit(self.centralwidget)
        self.frequency_InputWidget.setMaximumSize(QtCore.QSize(75, 16777215))
        self.frequency_InputWidget.setObjectName(_fromUtf8("frequency_InputWidget"))
        self.gridLayout.addWidget(self.frequency_InputWidget, 0, 2, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 0, 1, 7)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.idle_StateWidget = QtGui.QRadioButton(self.centralwidget)
        self.idle_StateWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.idle_StateWidget.setObjectName(_fromUtf8("idle_StateWidget"))
        self.gridLayout.addWidget(self.idle_StateWidget, 3, 0, 1, 1)
        self.power_InputWidget = QtGui.QLineEdit(self.centralwidget)
        self.power_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.power_InputWidget.setObjectName(_fromUtf8("power_InputWidget"))
        self.gridLayout.addWidget(self.power_InputWidget, 0, 4, 1, 1)
        self.elapsed_time_DisplayWidget = QtGui.QLCDNumber(self.centralwidget)
        self.elapsed_time_DisplayWidget.setObjectName(_fromUtf8("elapsed_time_DisplayWidget"))
        self.gridLayout.addWidget(self.elapsed_time_DisplayWidget, 3, 6, 1, 1)
        self.start_freq_InputWidget = QtGui.QLineEdit(self.centralwidget)
        self.start_freq_InputWidget.setMaximumSize(QtCore.QSize(75, 16777215))
        self.start_freq_InputWidget.setObjectName(_fromUtf8("start_freq_InputWidget"))
        self.gridLayout.addWidget(self.start_freq_InputWidget, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.run_StateWidget = QtGui.QRadioButton(self.centralwidget)
        self.run_StateWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.run_StateWidget.setObjectName(_fromUtf8("run_StateWidget"))
        self.gridLayout.addWidget(self.run_StateWidget, 3, 1, 1, 1)
        self.do_fit_PushButton = QtGui.QPushButton(self.centralwidget)
        self.do_fit_PushButton.setObjectName(_fromUtf8("do_fit_PushButton"))
        self.gridLayout.addWidget(self.do_fit_PushButton, 0, 10, 1, 1)
        self.odmr_cb_low_centile_InputWidget = QtGui.QSpinBox(self.centralwidget)
        self.odmr_cb_low_centile_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.odmr_cb_low_centile_InputWidget.setMaximum(100)
        self.odmr_cb_low_centile_InputWidget.setObjectName(_fromUtf8("odmr_cb_low_centile_InputWidget"))
        self.gridLayout.addWidget(self.odmr_cb_low_centile_InputWidget, 8, 13, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 8, 1, 1)
        self.fit_methods_ComboWidget = QtGui.QComboBox(self.centralwidget)
        self.fit_methods_ComboWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.fit_methods_ComboWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.fit_methods_ComboWidget.setObjectName(_fromUtf8("fit_methods_ComboWidget"))
        self.gridLayout.addWidget(self.fit_methods_ComboWidget, 0, 9, 1, 1)
        self.odmr_cb_high_centile_InputWidget = QtGui.QSpinBox(self.centralwidget)
        self.odmr_cb_high_centile_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.odmr_cb_high_centile_InputWidget.setMaximum(100)
        self.odmr_cb_high_centile_InputWidget.setProperty("value", 100)
        self.odmr_cb_high_centile_InputWidget.setObjectName(_fromUtf8("odmr_cb_high_centile_InputWidget"))
        self.gridLayout.addWidget(self.odmr_cb_high_centile_InputWidget, 5, 13, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 7, 4, 1)
        self.odmr_cb_manual_RadioButton = QtGui.QRadioButton(self.centralwidget)
        self.odmr_cb_manual_RadioButton.setObjectName(_fromUtf8("odmr_cb_manual_RadioButton"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.odmr_cb_manual_RadioButton)
        self.gridLayout.addWidget(self.odmr_cb_manual_RadioButton, 11, 12, 1, 2)
        self.odmr_cb_centiles_RadioButton = QtGui.QRadioButton(self.centralwidget)
        self.odmr_cb_centiles_RadioButton.setChecked(True)
        self.odmr_cb_centiles_RadioButton.setObjectName(_fromUtf8("odmr_cb_centiles_RadioButton"))
        self.buttonGroup.addButton(self.odmr_cb_centiles_RadioButton)
        self.gridLayout.addWidget(self.odmr_cb_centiles_RadioButton, 10, 12, 1, 2)
        self.odmr_ViewWidget = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.odmr_ViewWidget.sizePolicy().hasHeightForWidth())
        self.odmr_ViewWidget.setSizePolicy(sizePolicy)
        self.odmr_ViewWidget.setObjectName(_fromUtf8("odmr_ViewWidget"))
        self.gridLayout.addWidget(self.odmr_ViewWidget, 4, 0, 3, 12)
        self.odmr_matrix_ViewWidget = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.odmr_matrix_ViewWidget.sizePolicy().hasHeightForWidth())
        self.odmr_matrix_ViewWidget.setSizePolicy(sizePolicy)
        self.odmr_matrix_ViewWidget.setObjectName(_fromUtf8("odmr_matrix_ViewWidget"))
        self.gridLayout.addWidget(self.odmr_matrix_ViewWidget, 7, 0, 5, 12)
        self.odmr_fit_results_DisplayWidget = QtGui.QTextBrowser(self.centralwidget)
        self.odmr_fit_results_DisplayWidget.setObjectName(_fromUtf8("odmr_fit_results_DisplayWidget"))
        self.gridLayout.addWidget(self.odmr_fit_results_DisplayWidget, 1, 9, 3, 3)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 8, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Options = QtGui.QMenu(self.menubar)
        self.menu_Options.setObjectName(_fromUtf8("menu_Options"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Settings = QtGui.QAction(MainWindow)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))
        self.menu_Options.addAction(self.action_Settings)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.frequency_InputWidget, self.power_InputWidget)
        MainWindow.setTabOrder(self.power_InputWidget, self.start_freq_InputWidget)
        MainWindow.setTabOrder(self.start_freq_InputWidget, self.step_freq_InputWidget)
        MainWindow.setTabOrder(self.step_freq_InputWidget, self.stop_freq_InputWidget)
        MainWindow.setTabOrder(self.stop_freq_InputWidget, self.runtime_InputWidget)
        MainWindow.setTabOrder(self.runtime_InputWidget, self.mode_ComboWidget)
        MainWindow.setTabOrder(self.mode_ComboWidget, self.idle_StateWidget)
        MainWindow.setTabOrder(self.idle_StateWidget, self.run_StateWidget)
        MainWindow.setTabOrder(self.run_StateWidget, self.fit_methods_ComboWidget)
        MainWindow.setTabOrder(self.fit_methods_ComboWidget, self.do_fit_PushButton)
        MainWindow.setTabOrder(self.do_fit_PushButton, self.odmr_fit_results_DisplayWidget)
        MainWindow.setTabOrder(self.odmr_fit_results_DisplayWidget, self.odmr_cb_max_InputWidget)
        MainWindow.setTabOrder(self.odmr_cb_max_InputWidget, self.odmr_cb_high_centile_InputWidget)
        MainWindow.setTabOrder(self.odmr_cb_high_centile_InputWidget, self.odmr_cb_ViewWidget)
        MainWindow.setTabOrder(self.odmr_cb_ViewWidget, self.odmr_cb_low_centile_InputWidget)
        MainWindow.setTabOrder(self.odmr_cb_low_centile_InputWidget, self.odmr_cb_min_InputWidget)
        MainWindow.setTabOrder(self.odmr_cb_min_InputWidget, self.odmr_cb_centiles_RadioButton)
        MainWindow.setTabOrder(self.odmr_cb_centiles_RadioButton, self.odmr_cb_manual_RadioButton)
        MainWindow.setTabOrder(self.odmr_cb_manual_RadioButton, self.odmr_matrix_ViewWidget)
        MainWindow.setTabOrder(self.odmr_matrix_ViewWidget, self.odmr_ViewWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "qudi: ODMR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">% :</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">% :</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Elapsed Time [s] :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Runtime [s] :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Stop [MHz] :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Step [MHz] :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Mode :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Frequency [MHz] :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Start [MHz] :", None, QtGui.QApplication.UnicodeUTF8))
        self.idle_StateWidget.setText(QtGui.QApplication.translate("MainWindow", "Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Power [dBm] :", None, QtGui.QApplication.UnicodeUTF8))
        self.run_StateWidget.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.do_fit_PushButton.setText(QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Fit Function :", None, QtGui.QApplication.UnicodeUTF8))
        self.odmr_cb_manual_RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.odmr_cb_centiles_RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Centiles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Fit Results :", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Options.setTitle(QtGui.QApplication.translate("MainWindow", "&Options", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Settings.setText(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
