language: python

env:
  global:
    - SETUP_XVFB=True
    - CONDA_CHANNELS="qttesting"
    - CONDA_DEPENDENCIES="jedi jupyter lxml matplotlib numpy openssl pip pygments pyparsing python-dateutil pyzmq scipy sip six tornado traitlets"
    - PIP_DEPENDENCIES="fysom gitpython hdf5storage lmfit pydaqmx pyvisa pyvisa-py qtpy rpyc ruamel.yaml smmap spidev i2cdev"

  matrix:
    - PYTHON_VERSION=3.4 USE_QT_API=PyQt4
    - PYTHON_VERSION=3.4 USE_QT_API=PyQt5
    - PYTHON_VERSION=3.5 USE_QT_API=PyQt4
    - PYTHON_VERSION=3.5 USE_QT_API=PyQt5

before_install:
  # Test environments for different Qt bindings
  - if [[ "$USE_QT_API" == "PyQt5" ]]; then export CONDA_DEPENDENCIES='pyopengl qt=5.* pyqt=5.* '$CONDA_DEPENDENCIES; export QT_API=pyqt5;
    elif [[ "$USE_QT_API" == "PyQt4" ]]; then export CONDA_DEPENDENCIES='pyqtgraph qt=4.* pyqt=4.* '$CONDA_DEPENDENCIES; export QT_API=pyqt4;
    elif [[ "$USE_QT_API" == "PySide" ]]; then export CONDA_DEPENDENCIES='pyqtgraph qt=4.* pyside '$CONDA_DEPENDENCIES; export QT_API=pyside;
    fi
  - echo "$CONDA_DEPENDENCIES"
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - if [[ "$USE_QT_API" == "PyQt5" ]]; then
    git clone https://github.com/pyqtgraph/pyqtgraph.git;
    python pyqtgraph/setup.py install;
    fi

install:
  - python tools/qudikernel.py install

before_script:
  - "python start.py &"
  - sleep 5

script:
  - jupyter-nbconvert --execute notebooks/debug.ipynb
  - jupyter-nbconvert --execute notebooks/matplotlib.ipynb

after_script:
  - jupyter-nbconvert --execute notebooks/shutdown.ipynb
  - sleep 10
  - echo "======== QuDi Logfile ========"
  - cat qudi.log
  - if [ -e crash.log ]; then
      echo "======== QuDi Crashfile ========";
      cat crash.log;
    fi
