language: python

branches:
  except:
    - gh-pages

env:
  global:
    - SETUP_XVFB=True
#    - CONDA_CHANNELS="qttesting"
#    - CONDA_DEPENDENCIES="jedi jupyter lxml matplotlib numpy openssl pip pygments pyparsing python-dateutil pyzmq scipy sip six tornado traitlets"
#    - PIP_DEPENDENCIES="doxypypy fysom gitpython hdf5storage lmfit pydaqmx pyvisa pyvisa-py qtpy pyqtgraph rpyc ruamel.yaml smmap spidev i2cdev"

  matrix:
    - PYTHON_VERSION=3.6 USE_QT_API=PyQt5 BUILD_DOCS=True

addons:
  apt:
    sources:
      # for Doxygen
      - george-edison55-precise-backports
    packages:
     - graphviz

before_install:
  # Test environments for different Qt bindings
  - source tools/setup_conda_linux.sh
  - ./tools/install-python-modules-linux.sh
  - source activate qudi
  - mkdir -p $HOME/bin

install:
  - python -c "import matplotlib.pyplot" # generate matplotlib font cache
  - python core/qudikernel.py install
  - export PATH=$PATH:$HOME/bin

script:
  - ./tools/test.sh

after_success:
  - pip install doxypypy
  - echo -e "#!/bin/bash\ndoxypypy -a -c \$1" > $HOME/bin/py_filter
  - chmod +x $HOME/bin/py_filter
  - ./tools/travis-publish-doxygen.sh

