language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.4"
  - "3.5"
addons:
 apt:
   packages:
   - python3-setuptools
   - python3-fysom
   - python3-lmfit
   - python3-pyqt4
   - python3-numpy
   - python3-scipy
   - python3-zmq
   - python3-sip
   - python3-pygments
   - python3-lxml
   - build-essential
   - devscripts
env:
  - DISPLAY=:99.0
install:
  - pip install --user -r tools/requirements.txt
  - python tools/qudikernel.py install
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "python start.py &"
script:
  - jupyter-nbconvert --execute notebooks/debug.ipynb
  - jupyter-nbconvert --execute notebooks/matplotlib.ipynb
after_script:
  - jupyter-nbconvert --execute notebooks/shutdown.ipynb
  - sleep 10
  - echo "======== QuDi Logfile ========"
  - cat qudi.log
  - if [ -e crash.log ]; then echo "======== QuDi Crashfile ========"; cat crash.log; fi
