
#branches:
#  only:
#    - master

environment:
  global:
      PYTHON: "C:\\conda"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      # Used by atropy ci-helpers
      CONDA_CHANNELS: "qttesting"

  matrix:
    # Qt4
    - PYTHON_VERSION: "3.4"
      CONDA_DEPENDENCIES: "jedi jupyter lxml matplotlib numpy openssl pip pygments pyzmq scipy sip six traitlets qt=4.8.7 pyqt=4.10.4"
      PIP_DEPENDENCIES: "pyqtgraph fysom gitpython hdf5storage lmfit pydaqmx pyvisa pyvisa-py qtpy rpyc ruamel.yaml smmap"
      QT_API: "pyqt4"
    - PYTHON_VERSION: "3.5"
      CONDA_DEPENDENCIES: "jedi jupyter lxml matplotlib numpy openssl pip pygments pyzmq scipy sip six traitlets qt=4.* pyqt=4.*"
      PIP_DEPENDENCIES: "pyqtgraph fysom gitpython hdf5storage lmfit pydaqmx pyvisa pyvisa-py qtpy rpyc ruamel.yaml smmap"
      QT_API: "pyqt4"
    # Qt5
    - PYTHON_VERSION: "3.4"
      CONDA_DEPENDENCIES: "jedi jupyter lxml matplotlib numpy openssl pip pygments pyopengl pyzmq scipy sip six traitlets qt=5.* pyqt=5.*"
      PIP_DEPENDENCIES: "pyqtgraph fysom gitpython hdf5storage lmfit pydaqmx pyvisa pyvisa-py qtpy rpyc ruamel.yaml smmap"
      QT_API: "pyqt5"
    - PYTHON_VERSION: "3.5"
      CONDA_DEPENDENCIES: "jedi jupyter lxml matplotlib numpy openssl pip pygments pyopengl pyzmq scipy sip six traitlets qt=5.* pyqt=5.*"
      PIP_DEPENDENCIES: "pyqtgraph fysom gitpython hdf5storage lmfit pydaqmx pyvisa pyvisa-py qtpy rpyc ruamel.yaml smmap"
      QT_API: "pyqt5"

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "python tools\\qudikernel.py install"
#    - ps: |
#        if ($env:QT_API -eq "pyqt5") {
#            push-location
#            cmd /c 'git clone https://github.com/pyqtgraph/pyqtgraph.git pyqtgraph-github 2>&1'
#            cd pyqtgraph-github
#            cmd /c 'python setup.py install 2>&1'
#            pop-location
#        }

# Not a .NET project, we build in the install step instead
build: false

test_script:
    - sh "tools\\test.sh"

