
#branches:
#  only:
#    - master

environment:
  global:
      PYTHON: "C:\\miniconda"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.

platform:
    -x64

install:
    - "powershell %~dp0\\setup_conda_windows.ps"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "conda env remove --yes --name qudi"
    - "conda env create -f %~dp0\\conda-env-win8-qt5.yml"
    - "activate qudi"
    - "python %~dp0\\qudikernel.py install"

# Not a .NET project, we build in the install step instead
build: false

test_script:
    - sh "tools\\test.sh"

