# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_poimangui.ui'
#
# Created: Wed Jul  1 16:44:27 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PoiManager(object):
    def setupUi(self, PoiManager):
        PoiManager.setObjectName(_fromUtf8("PoiManager"))
        PoiManager.resize(677, 747)
        PoiManager.setTabShape(QtGui.QTabWidget.Triangular)
        PoiManager.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(PoiManager)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        PoiManager.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PoiManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        PoiManager.setMenuBar(self.menubar)
        self.roi_ToolBar = QtGui.QToolBar(PoiManager)
        self.roi_ToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.roi_ToolBar.setObjectName(_fromUtf8("roi_ToolBar"))
        PoiManager.addToolBar(QtCore.Qt.TopToolBarArea, self.roi_ToolBar)
        self.poi_editor_dockWidget = QtGui.QDockWidget(PoiManager)
        self.poi_editor_dockWidget.setObjectName(_fromUtf8("poi_editor_dockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.set_poi_PushButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.set_poi_PushButton.setObjectName(_fromUtf8("set_poi_PushButton"))
        self.verticalLayout_6.addWidget(self.set_poi_PushButton)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label = QtGui.QLabel(self.dockWidgetContents_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_13.addWidget(self.label)
        self.active_poi_ComboBox = QtGui.QComboBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_poi_ComboBox.sizePolicy().hasHeightForWidth())
        self.active_poi_ComboBox.setSizePolicy(sizePolicy)
        self.active_poi_ComboBox.setEditable(False)
        self.active_poi_ComboBox.setObjectName(_fromUtf8("active_poi_ComboBox"))
        self.horizontalLayout_13.addWidget(self.active_poi_ComboBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_14.addWidget(self.label_3)
        self.poi_name_LineEdit = QtGui.QLineEdit(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.poi_name_LineEdit.sizePolicy().hasHeightForWidth())
        self.poi_name_LineEdit.setSizePolicy(sizePolicy)
        self.poi_name_LineEdit.setObjectName(_fromUtf8("poi_name_LineEdit"))
        self.horizontalLayout_14.addWidget(self.poi_name_LineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.delete_poi_PushButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.delete_poi_PushButton.setObjectName(_fromUtf8("delete_poi_PushButton"))
        self.verticalLayout_6.addWidget(self.delete_poi_PushButton)
        self.label_9 = QtGui.QLabel(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_6.addWidget(self.label_9)
        self.poi_coords_label = QtGui.QLabel(self.dockWidgetContents_3)
        self.poi_coords_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.poi_coords_label.setObjectName(_fromUtf8("poi_coords_label"))
        self.verticalLayout_6.addWidget(self.poi_coords_label)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.poi_editor_dockWidget.setWidget(self.dockWidgetContents_3)
        PoiManager.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.poi_editor_dockWidget)
        self.poi_tracker_dockWidget = QtGui.QDockWidget(PoiManager)
        self.poi_tracker_dockWidget.setFloating(False)
        self.poi_tracker_dockWidget.setObjectName(_fromUtf8("poi_tracker_dockWidget"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_7)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.goto_poi_PushButton = QtGui.QPushButton(self.dockWidgetContents_7)
        self.goto_poi_PushButton.setObjectName(_fromUtf8("goto_poi_PushButton"))
        self.horizontalLayout_7.addWidget(self.goto_poi_PushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.refind_poi_PushButton = QtGui.QPushButton(self.dockWidgetContents_7)
        self.refind_poi_PushButton.setObjectName(_fromUtf8("refind_poi_PushButton"))
        self.horizontalLayout_2.addWidget(self.refind_poi_PushButton)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_7)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.refind_method_ComboBox = QtGui.QComboBox(self.dockWidgetContents_7)
        self.refind_method_ComboBox.setObjectName(_fromUtf8("refind_method_ComboBox"))
        self.refind_method_ComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.refind_method_ComboBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.goto_poi_after_update_checkBox = QtGui.QCheckBox(self.dockWidgetContents_7)
        self.goto_poi_after_update_checkBox.setChecked(True)
        self.goto_poi_after_update_checkBox.setObjectName(_fromUtf8("goto_poi_after_update_checkBox"))
        self.horizontalLayout_3.addWidget(self.goto_poi_after_update_checkBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.delete_last_pos_Button = QtGui.QPushButton(self.dockWidgetContents_7)
        self.delete_last_pos_Button.setObjectName(_fromUtf8("delete_last_pos_Button"))
        self.horizontalLayout_8.addWidget(self.delete_last_pos_Button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.periodic_update_CheckBox = QtGui.QCheckBox(self.dockWidgetContents_7)
        self.periodic_update_CheckBox.setObjectName(_fromUtf8("periodic_update_CheckBox"))
        self.horizontalLayout_11.addWidget(self.periodic_update_CheckBox)
        self.track_period_SpinBox = QtGui.QSpinBox(self.dockWidgetContents_7)
        self.track_period_SpinBox.setMinimum(5)
        self.track_period_SpinBox.setMaximum(999)
        self.track_period_SpinBox.setSingleStep(5)
        self.track_period_SpinBox.setProperty("value", 15)
        self.track_period_SpinBox.setObjectName(_fromUtf8("track_period_SpinBox"))
        self.horizontalLayout_11.addWidget(self.track_period_SpinBox)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_7)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_11.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.time_till_next_update_ProgressBar = QtGui.QProgressBar(self.dockWidgetContents_7)
        self.time_till_next_update_ProgressBar.setMaximum(15)
        self.time_till_next_update_ProgressBar.setProperty("value", 15)
        self.time_till_next_update_ProgressBar.setObjectName(_fromUtf8("time_till_next_update_ProgressBar"))
        self.verticalLayout_5.addWidget(self.time_till_next_update_ProgressBar)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.manual_update_poi_PushButton = QtGui.QPushButton(self.dockWidgetContents_7)
        self.manual_update_poi_PushButton.setObjectName(_fromUtf8("manual_update_poi_PushButton"))
        self.horizontalLayout_12.addWidget(self.manual_update_poi_PushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.poi_tracker_dockWidget.setWidget(self.dockWidgetContents_7)
        PoiManager.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.poi_tracker_dockWidget)
        self.roi_map_dockWidget = QtGui.QDockWidget(PoiManager)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roi_map_dockWidget.sizePolicy().hasHeightForWidth())
        self.roi_map_dockWidget.setSizePolicy(sizePolicy)
        self.roi_map_dockWidget.setObjectName(_fromUtf8("roi_map_dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.get_confocal_image_PushButton = QtGui.QPushButton(self.dockWidgetContents)
        self.get_confocal_image_PushButton.setObjectName(_fromUtf8("get_confocal_image_PushButton"))
        self.verticalLayout_2.addWidget(self.get_confocal_image_PushButton)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.roi_map_ViewWidget = PlotWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.roi_map_ViewWidget.sizePolicy().hasHeightForWidth())
        self.roi_map_ViewWidget.setSizePolicy(sizePolicy)
        self.roi_map_ViewWidget.setObjectName(_fromUtf8("roi_map_ViewWidget"))
        self.horizontalLayout_10.addWidget(self.roi_map_ViewWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.roi_cb_max_SpinBox = QtGui.QSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roi_cb_max_SpinBox.sizePolicy().hasHeightForWidth())
        self.roi_cb_max_SpinBox.setSizePolicy(sizePolicy)
        self.roi_cb_max_SpinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.roi_cb_max_SpinBox.setMouseTracking(True)
        self.roi_cb_max_SpinBox.setAcceptDrops(True)
        self.roi_cb_max_SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_cb_max_SpinBox.setAccelerated(True)
        self.roi_cb_max_SpinBox.setMinimum(-100000000)
        self.roi_cb_max_SpinBox.setMaximum(100000000)
        self.roi_cb_max_SpinBox.setSingleStep(1000)
        self.roi_cb_max_SpinBox.setProperty("value", 100000)
        self.roi_cb_max_SpinBox.setObjectName(_fromUtf8("roi_cb_max_SpinBox"))
        self.verticalLayout.addWidget(self.roi_cb_max_SpinBox)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.roi_cb_high_centile_SpinBox = QtGui.QSpinBox(self.dockWidgetContents)
        self.roi_cb_high_centile_SpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.roi_cb_high_centile_SpinBox.setMinimum(0)
        self.roi_cb_high_centile_SpinBox.setMaximum(100)
        self.roi_cb_high_centile_SpinBox.setProperty("value", 100)
        self.roi_cb_high_centile_SpinBox.setObjectName(_fromUtf8("roi_cb_high_centile_SpinBox"))
        self.horizontalLayout_9.addWidget(self.roi_cb_high_centile_SpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.roi_cb_ViewWidget = PlotWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roi_cb_ViewWidget.sizePolicy().hasHeightForWidth())
        self.roi_cb_ViewWidget.setSizePolicy(sizePolicy)
        self.roi_cb_ViewWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.roi_cb_ViewWidget.setObjectName(_fromUtf8("roi_cb_ViewWidget"))
        self.verticalLayout.addWidget(self.roi_cb_ViewWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.roi_cb_low_centile_SpinBox = QtGui.QSpinBox(self.dockWidgetContents)
        self.roi_cb_low_centile_SpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.roi_cb_low_centile_SpinBox.setMaximum(100)
        self.roi_cb_low_centile_SpinBox.setProperty("value", 0)
        self.roi_cb_low_centile_SpinBox.setObjectName(_fromUtf8("roi_cb_low_centile_SpinBox"))
        self.horizontalLayout_4.addWidget(self.roi_cb_low_centile_SpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.roi_cb_min_SpinBox = QtGui.QSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roi_cb_min_SpinBox.sizePolicy().hasHeightForWidth())
        self.roi_cb_min_SpinBox.setSizePolicy(sizePolicy)
        self.roi_cb_min_SpinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.roi_cb_min_SpinBox.setMouseTracking(True)
        self.roi_cb_min_SpinBox.setAcceptDrops(True)
        self.roi_cb_min_SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_cb_min_SpinBox.setAccelerated(True)
        self.roi_cb_min_SpinBox.setMinimum(-100000000)
        self.roi_cb_min_SpinBox.setMaximum(100000000)
        self.roi_cb_min_SpinBox.setSingleStep(1000)
        self.roi_cb_min_SpinBox.setProperty("value", 100)
        self.roi_cb_min_SpinBox.setObjectName(_fromUtf8("roi_cb_min_SpinBox"))
        self.verticalLayout.addWidget(self.roi_cb_min_SpinBox)
        self.roi_cb_centiles_RadioButton = QtGui.QRadioButton(self.dockWidgetContents)
        self.roi_cb_centiles_RadioButton.setChecked(True)
        self.roi_cb_centiles_RadioButton.setObjectName(_fromUtf8("roi_cb_centiles_RadioButton"))
        self.verticalLayout.addWidget(self.roi_cb_centiles_RadioButton)
        self.roi_cb_manual_RadioButton = QtGui.QRadioButton(self.dockWidgetContents)
        self.roi_cb_manual_RadioButton.setChecked(False)
        self.roi_cb_manual_RadioButton.setObjectName(_fromUtf8("roi_cb_manual_RadioButton"))
        self.verticalLayout.addWidget(self.roi_cb_manual_RadioButton)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.roi_map_dockWidget.setWidget(self.dockWidgetContents)
        PoiManager.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.roi_map_dockWidget)
        self.sample_shift_dockWidget = QtGui.QDockWidget(PoiManager)
        self.sample_shift_dockWidget.setObjectName(_fromUtf8("sample_shift_dockWidget"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.dispay_shift_vs_duration_RadioButton = QtGui.QRadioButton(self.dockWidgetContents_6)
        self.dispay_shift_vs_duration_RadioButton.setChecked(True)
        self.dispay_shift_vs_duration_RadioButton.setObjectName(_fromUtf8("dispay_shift_vs_duration_RadioButton"))
        self.horizontalLayout_6.addWidget(self.dispay_shift_vs_duration_RadioButton)
        self.dispay_shift_vs_clocktime_RadioButton = QtGui.QRadioButton(self.dockWidgetContents_6)
        self.dispay_shift_vs_clocktime_RadioButton.setObjectName(_fromUtf8("dispay_shift_vs_clocktime_RadioButton"))
        self.horizontalLayout_6.addWidget(self.dispay_shift_vs_clocktime_RadioButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.sample_shift_ViewWidget = PlotWidget(self.dockWidgetContents_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.sample_shift_ViewWidget.sizePolicy().hasHeightForWidth())
        self.sample_shift_ViewWidget.setSizePolicy(sizePolicy)
        self.sample_shift_ViewWidget.setObjectName(_fromUtf8("sample_shift_ViewWidget"))
        self.verticalLayout_4.addWidget(self.sample_shift_ViewWidget)
        self.sample_shift_dockWidget.setWidget(self.dockWidgetContents_6)
        PoiManager.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.sample_shift_dockWidget)
        self.poi_ToolBar = QtGui.QToolBar(PoiManager)
        self.poi_ToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.poi_ToolBar.setObjectName(_fromUtf8("poi_ToolBar"))
        PoiManager.addToolBar(QtCore.Qt.TopToolBarArea, self.poi_ToolBar)
        self.actionNew_ROI = QtGui.QAction(PoiManager)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.actionNew_ROI.setIcon(icon)
        self.actionNew_ROI.setObjectName(_fromUtf8("actionNew_ROI"))
        self.actionSave_ROI = QtGui.QAction(PoiManager)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave_ROI.setIcon(icon)
        self.actionSave_ROI.setObjectName(_fromUtf8("actionSave_ROI"))
        self.actionOpen_ROI = QtGui.QAction(PoiManager)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.actionOpen_ROI.setIcon(icon)
        self.actionOpen_ROI.setObjectName(_fromUtf8("actionOpen_ROI"))
        self.actionNew_POI = QtGui.QAction(PoiManager)
        self.actionNew_POI.setObjectName(_fromUtf8("actionNew_POI"))
        self.actionColorbar = QtGui.QAction(PoiManager)
        self.actionColorbar.setObjectName(_fromUtf8("actionColorbar"))
        self.actionPOI_Editor_view = QtGui.QAction(PoiManager)
        self.actionPOI_Editor_view.setCheckable(True)
        self.actionPOI_Editor_view.setChecked(True)
        self.actionPOI_Editor_view.setObjectName(_fromUtf8("actionPOI_Editor_view"))
        self.actionPOI_Tracker_view = QtGui.QAction(PoiManager)
        self.actionPOI_Tracker_view.setCheckable(True)
        self.actionPOI_Tracker_view.setChecked(True)
        self.actionPOI_Tracker_view.setObjectName(_fromUtf8("actionPOI_Tracker_view"))
        self.actionSample_shfit_view = QtGui.QAction(PoiManager)
        self.actionSample_shfit_view.setCheckable(True)
        self.actionSample_shfit_view.setChecked(True)
        self.actionSample_shfit_view.setObjectName(_fromUtf8("actionSample_shfit_view"))
        self.actionROI_Map_view = QtGui.QAction(PoiManager)
        self.actionROI_Map_view.setCheckable(True)
        self.actionROI_Map_view.setChecked(True)
        self.actionROI_Map_view.setObjectName(_fromUtf8("actionROI_Map_view"))
        self.refind_poi_Action = QtGui.QAction(PoiManager)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("optimize_position_poi"))
        self.refind_poi_Action.setIcon(icon)
        self.refind_poi_Action.setObjectName(_fromUtf8("refind_poi_Action"))
        self.track_poi_Action = QtGui.QAction(PoiManager)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("periodic_refind_poi"))
        self.track_poi_Action.setIcon(icon)
        self.track_poi_Action.setObjectName(_fromUtf8("track_poi_Action"))
        self.new_poi_Action = QtGui.QAction(PoiManager)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("poi-add-new"))
        self.new_poi_Action.setIcon(icon)
        self.new_poi_Action.setObjectName(_fromUtf8("new_poi_Action"))
        self.menuMenu.addAction(self.actionNew_ROI)
        self.menuMenu.addAction(self.actionOpen_ROI)
        self.menuMenu.addAction(self.actionSave_ROI)
        self.menuView.addAction(self.actionROI_Map_view)
        self.menuView.addAction(self.actionPOI_Editor_view)
        self.menuView.addAction(self.actionPOI_Tracker_view)
        self.menuView.addAction(self.actionSample_shfit_view)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.roi_ToolBar.addAction(self.actionNew_ROI)
        self.roi_ToolBar.addSeparator()
        self.poi_ToolBar.addAction(self.new_poi_Action)
        self.poi_ToolBar.addAction(self.refind_poi_Action)
        self.poi_ToolBar.addAction(self.track_poi_Action)

        self.retranslateUi(PoiManager)
        QtCore.QObject.connect(self.actionPOI_Editor_view, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.poi_editor_dockWidget.setVisible)
        QtCore.QObject.connect(self.poi_editor_dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionPOI_Editor_view.setChecked)
        QtCore.QObject.connect(self.actionROI_Map_view, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.roi_map_dockWidget.setVisible)
        QtCore.QObject.connect(self.roi_map_dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionROI_Map_view.setChecked)
        QtCore.QObject.connect(self.actionPOI_Tracker_view, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.poi_tracker_dockWidget.setVisible)
        QtCore.QObject.connect(self.poi_tracker_dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionPOI_Tracker_view.setChecked)
        QtCore.QObject.connect(self.actionSample_shfit_view, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.sample_shift_dockWidget.setVisible)
        QtCore.QObject.connect(self.sample_shift_dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionSample_shfit_view.setChecked)
        QtCore.QMetaObject.connectSlotsByName(PoiManager)

    def retranslateUi(self, PoiManager):
        PoiManager.setWindowTitle(_translate("PoiManager", "qudi: POI Manager", None))
        self.menuMenu.setTitle(_translate("PoiManager", "Menu", None))
        self.menuView.setTitle(_translate("PoiManager", "View", None))
        self.roi_ToolBar.setWindowTitle(_translate("PoiManager", "toolBar", None))
        self.poi_editor_dockWidget.setWindowTitle(_translate("PoiManager", "POI Editor", None))
        self.set_poi_PushButton.setToolTip(_translate("PoiManager", "Set current cursor position as a new trackpoint in the ROI map", None))
        self.set_poi_PushButton.setText(_translate("PoiManager", "Set new POI", None))
        self.label.setText(_translate("PoiManager", "Select:", None))
        self.label_3.setText(_translate("PoiManager", "Rename:", None))
        self.delete_poi_PushButton.setText(_translate("PoiManager", "Delete POI", None))
        self.label_9.setText(_translate("PoiManager", "(x,y,z):", None))
        self.poi_coords_label.setToolTip(_translate("PoiManager", "This text is selectable.  Copy and paste into labnotes.", None))
        self.poi_coords_label.setText(_translate("PoiManager", "(?, ?, ?)", None))
        self.poi_tracker_dockWidget.setWindowTitle(_translate("PoiManager", "POI Tracker", None))
        self.goto_poi_PushButton.setText(_translate("PoiManager", "Go to POI", None))
        self.refind_poi_PushButton.setText(_translate("PoiManager", "Refind POI", None))
        self.label_4.setText(_translate("PoiManager", "using", None))
        self.refind_method_ComboBox.setItemText(0, _translate("PoiManager", "position optimisation", None))
        self.goto_poi_after_update_checkBox.setToolTip(_translate("PoiManager", "Move crosshair to updated POI position afterwards.", None))
        self.goto_poi_after_update_checkBox.setText(_translate("PoiManager", "Follow", None))
        self.delete_last_pos_Button.setText(_translate("PoiManager", "Delete last position", None))
        self.periodic_update_CheckBox.setText(_translate("PoiManager", "Refind every", None))
        self.label_6.setText(_translate("PoiManager", "seconds", None))
        self.time_till_next_update_ProgressBar.setFormat(_translate("PoiManager", "%v s", None))
        self.manual_update_poi_PushButton.setToolTip(_translate("PoiManager", "This is for telling QuDi a totally new position for a known trackpoint.  For example, after manually shifting the sample to re-centre the ROI in the scan range.", None))
        self.manual_update_poi_PushButton.setText(_translate("PoiManager", "Manual update position", None))
        self.roi_map_dockWidget.setWindowTitle(_translate("PoiManager", "ROI Map", None))
        self.get_confocal_image_PushButton.setText(_translate("PoiManager", "Get Confocal image", None))
        self.label_5.setText(_translate("PoiManager", "%", None))
        self.label_2.setText(_translate("PoiManager", "%", None))
        self.roi_cb_centiles_RadioButton.setText(_translate("PoiManager", "Centiles", None))
        self.roi_cb_manual_RadioButton.setText(_translate("PoiManager", "Manual", None))
        self.sample_shift_dockWidget.setWindowTitle(_translate("PoiManager", "Sample shift", None))
        self.dispay_shift_vs_duration_RadioButton.setText(_translate("PoiManager", "Duration (seconds)", None))
        self.dispay_shift_vs_clocktime_RadioButton.setText(_translate("PoiManager", "Clock time", None))
        self.poi_ToolBar.setWindowTitle(_translate("PoiManager", "toolBar", None))
        self.actionNew_ROI.setText(_translate("PoiManager", "New ROI", None))
        self.actionNew_ROI.setToolTip(_translate("PoiManager", "Start a new ROI (such as after moving to a different part of the sample", None))
        self.actionSave_ROI.setText(_translate("PoiManager", "Save ROI", None))
        self.actionSave_ROI.setToolTip(_translate("PoiManager", "Save ROI for future reuse", None))
        self.actionOpen_ROI.setText(_translate("PoiManager", "Open ROI", None))
        self.actionOpen_ROI.setToolTip(_translate("PoiManager", "Load a saved ROI", None))
        self.actionNew_POI.setText(_translate("PoiManager", "New POI", None))
        self.actionColorbar.setText(_translate("PoiManager", "Colorbar", None))
        self.actionPOI_Editor_view.setText(_translate("PoiManager", "POI Editor", None))
        self.actionPOI_Editor_view.setShortcut(_translate("PoiManager", "Alt+E", None))
        self.actionPOI_Tracker_view.setText(_translate("PoiManager", "POI Tracker", None))
        self.actionPOI_Tracker_view.setShortcut(_translate("PoiManager", "Alt+T", None))
        self.actionSample_shfit_view.setText(_translate("PoiManager", "Sample shfit", None))
        self.actionSample_shfit_view.setShortcut(_translate("PoiManager", "Alt+S", None))
        self.actionROI_Map_view.setText(_translate("PoiManager", "ROI Map", None))
        self.actionROI_Map_view.setShortcut(_translate("PoiManager", "Alt+M", None))
        self.refind_poi_Action.setText(_translate("PoiManager", "Refind POI", None))
        self.refind_poi_Action.setToolTip(_translate("PoiManager", "Refind the POI using the strategy selected in the POI control dock", None))
        self.track_poi_Action.setText(_translate("PoiManager", "Track POI", None))
        self.track_poi_Action.setToolTip(_translate("PoiManager", "Track the POI by periodically refinding its position", None))
        self.new_poi_Action.setText(_translate("PoiManager", "New POI", None))
        self.new_poi_Action.setToolTip(_translate("PoiManager", "Add a new POI at the current crosshair position", None))

from pyqtgraph import PlotWidget
