# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_confocalgui.ui'
#
# Created: Wed Jul  1 11:43:04 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1255, 939)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1255, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Options = QtGui.QMenu(self.menubar)
        self.menu_Options.setObjectName(_fromUtf8("menu_Options"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.depth_scan_dockWidget = QtGui.QDockWidget(MainWindow)
        self.depth_scan_dockWidget.setObjectName(_fromUtf8("depth_scan_dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.depth_ViewWidget = PlotWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_ViewWidget.sizePolicy().hasHeightForWidth())
        self.depth_ViewWidget.setSizePolicy(sizePolicy)
        self.depth_ViewWidget.setObjectName(_fromUtf8("depth_ViewWidget"))
        self.horizontalLayout_5.addWidget(self.depth_ViewWidget)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.depth_cb_max_InputWidget = QtGui.QSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_cb_max_InputWidget.sizePolicy().hasHeightForWidth())
        self.depth_cb_max_InputWidget.setSizePolicy(sizePolicy)
        self.depth_cb_max_InputWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.depth_cb_max_InputWidget.setMouseTracking(True)
        self.depth_cb_max_InputWidget.setAcceptDrops(True)
        self.depth_cb_max_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depth_cb_max_InputWidget.setMinimum(-100000000)
        self.depth_cb_max_InputWidget.setMaximum(100000000)
        self.depth_cb_max_InputWidget.setSingleStep(1000)
        self.depth_cb_max_InputWidget.setProperty("value", 100000)
        self.depth_cb_max_InputWidget.setObjectName(_fromUtf8("depth_cb_max_InputWidget"))
        self.verticalLayout_2.addWidget(self.depth_cb_max_InputWidget)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_12 = QtGui.QLabel(self.dockWidgetContents)
        self.label_12.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.depth_cb_high_centile_InputWidget = QtGui.QSpinBox(self.dockWidgetContents)
        self.depth_cb_high_centile_InputWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.depth_cb_high_centile_InputWidget.setMinimum(0)
        self.depth_cb_high_centile_InputWidget.setMaximum(100)
        self.depth_cb_high_centile_InputWidget.setProperty("value", 100)
        self.depth_cb_high_centile_InputWidget.setObjectName(_fromUtf8("depth_cb_high_centile_InputWidget"))
        self.horizontalLayout_11.addWidget(self.depth_cb_high_centile_InputWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.depth_cb_ViewWidget = PlotWidget(self.dockWidgetContents)
        self.depth_cb_ViewWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.depth_cb_ViewWidget.setObjectName(_fromUtf8("depth_cb_ViewWidget"))
        self.verticalLayout_2.addWidget(self.depth_cb_ViewWidget)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents)
        self.label_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.depth_cb_low_centile_InputWidget = QtGui.QSpinBox(self.dockWidgetContents)
        self.depth_cb_low_centile_InputWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.depth_cb_low_centile_InputWidget.setMaximum(100)
        self.depth_cb_low_centile_InputWidget.setProperty("value", 0)
        self.depth_cb_low_centile_InputWidget.setObjectName(_fromUtf8("depth_cb_low_centile_InputWidget"))
        self.horizontalLayout_10.addWidget(self.depth_cb_low_centile_InputWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.depth_cb_min_InputWidget = QtGui.QSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_cb_min_InputWidget.sizePolicy().hasHeightForWidth())
        self.depth_cb_min_InputWidget.setSizePolicy(sizePolicy)
        self.depth_cb_min_InputWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.depth_cb_min_InputWidget.setMouseTracking(True)
        self.depth_cb_min_InputWidget.setAcceptDrops(True)
        self.depth_cb_min_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depth_cb_min_InputWidget.setAccelerated(True)
        self.depth_cb_min_InputWidget.setMinimum(-100000000)
        self.depth_cb_min_InputWidget.setMaximum(100000000)
        self.depth_cb_min_InputWidget.setSingleStep(1000)
        self.depth_cb_min_InputWidget.setProperty("value", 100)
        self.depth_cb_min_InputWidget.setObjectName(_fromUtf8("depth_cb_min_InputWidget"))
        self.verticalLayout_2.addWidget(self.depth_cb_min_InputWidget)
        self.depth_cb_centiles_RadioButton = QtGui.QRadioButton(self.dockWidgetContents)
        self.depth_cb_centiles_RadioButton.setChecked(True)
        self.depth_cb_centiles_RadioButton.setObjectName(_fromUtf8("depth_cb_centiles_RadioButton"))
        self.verticalLayout_2.addWidget(self.depth_cb_centiles_RadioButton)
        self.depth_cb_manual_RadioButton = QtGui.QRadioButton(self.dockWidgetContents)
        self.depth_cb_manual_RadioButton.setChecked(False)
        self.depth_cb_manual_RadioButton.setObjectName(_fromUtf8("depth_cb_manual_RadioButton"))
        self.verticalLayout_2.addWidget(self.depth_cb_manual_RadioButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.depth_scan_dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.depth_scan_dockWidget)
        self.optimizer_dockWidget = QtGui.QDockWidget(MainWindow)
        self.optimizer_dockWidget.setObjectName(_fromUtf8("optimizer_dockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.xy_refocus_ViewWidget_2 = PlotWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.xy_refocus_ViewWidget_2.sizePolicy().hasHeightForWidth())
        self.xy_refocus_ViewWidget_2.setSizePolicy(sizePolicy)
        self.xy_refocus_ViewWidget_2.setMinimumSize(QtCore.QSize(220, 220))
        self.xy_refocus_ViewWidget_2.setMaximumSize(QtCore.QSize(220, 220))
        self.xy_refocus_ViewWidget_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.xy_refocus_ViewWidget_2.setBaseSize(QtCore.QSize(0, 0))
        self.xy_refocus_ViewWidget_2.setObjectName(_fromUtf8("xy_refocus_ViewWidget_2"))
        self.horizontalLayout_12.addWidget(self.xy_refocus_ViewWidget_2)
        self.depth_refocus_ViewWidget_2 = PlotWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_refocus_ViewWidget_2.sizePolicy().hasHeightForWidth())
        self.depth_refocus_ViewWidget_2.setSizePolicy(sizePolicy)
        self.depth_refocus_ViewWidget_2.setMinimumSize(QtCore.QSize(0, 220))
        self.depth_refocus_ViewWidget_2.setObjectName(_fromUtf8("depth_refocus_ViewWidget_2"))
        self.horizontalLayout_12.addWidget(self.depth_refocus_ViewWidget_2)
        self.horizontalLayout_12.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_9 = QtGui.QLabel(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_13.addWidget(self.label_9)
        self.refocus_position_label = QtGui.QLabel(self.dockWidgetContents_2)
        self.refocus_position_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.refocus_position_label.setObjectName(_fromUtf8("refocus_position_label"))
        self.horizontalLayout_13.addWidget(self.refocus_position_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.optimizer_dockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.optimizer_dockWidget)
        self.scan_control_dockWidget = QtGui.QDockWidget(MainWindow)
        self.scan_control_dockWidget.setMaximumSize(QtCore.QSize(524287, 140))
        self.scan_control_dockWidget.setObjectName(_fromUtf8("scan_control_dockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem1 = QtGui.QSpacerItem(56, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.line = QtGui.QFrame(self.dockWidgetContents_3)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_7.addWidget(self.line)
        spacerItem2 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.xy_res_InputWidget = QtGui.QSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_res_InputWidget.sizePolicy().hasHeightForWidth())
        self.xy_res_InputWidget.setSizePolicy(sizePolicy)
        self.xy_res_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.xy_res_InputWidget.setMouseTracking(True)
        self.xy_res_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.xy_res_InputWidget.setAcceptDrops(True)
        self.xy_res_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xy_res_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.xy_res_InputWidget.setAccelerated(True)
        self.xy_res_InputWidget.setMaximum(10000)
        self.xy_res_InputWidget.setObjectName(_fromUtf8("xy_res_InputWidget"))
        self.horizontalLayout.addWidget(self.xy_res_InputWidget)
        self.line_2 = QtGui.QFrame(self.dockWidgetContents_3)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.x_min_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_min_InputWidget.sizePolicy().hasHeightForWidth())
        self.x_min_InputWidget.setSizePolicy(sizePolicy)
        self.x_min_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_min_InputWidget.setMouseTracking(True)
        self.x_min_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.x_min_InputWidget.setAcceptDrops(True)
        self.x_min_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_min_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.x_min_InputWidget.setAccelerated(True)
        self.x_min_InputWidget.setDecimals(2)
        self.x_min_InputWidget.setMinimum(-200.0)
        self.x_min_InputWidget.setMaximum(200.0)
        self.x_min_InputWidget.setSingleStep(1.0)
        self.x_min_InputWidget.setObjectName(_fromUtf8("x_min_InputWidget"))
        self.horizontalLayout.addWidget(self.x_min_InputWidget)
        self.x_max_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_max_InputWidget.sizePolicy().hasHeightForWidth())
        self.x_max_InputWidget.setSizePolicy(sizePolicy)
        self.x_max_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_max_InputWidget.setMouseTracking(True)
        self.x_max_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.x_max_InputWidget.setAcceptDrops(True)
        self.x_max_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_max_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.x_max_InputWidget.setAccelerated(True)
        self.x_max_InputWidget.setMinimum(-200.0)
        self.x_max_InputWidget.setMaximum(200.0)
        self.x_max_InputWidget.setObjectName(_fromUtf8("x_max_InputWidget"))
        self.horizontalLayout.addWidget(self.x_max_InputWidget)
        self.x_SliderWidget = QtGui.QSlider(self.dockWidgetContents_3)
        self.x_SliderWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.x_SliderWidget.setSingleStep(1)
        self.x_SliderWidget.setOrientation(QtCore.Qt.Horizontal)
        self.x_SliderWidget.setObjectName(_fromUtf8("x_SliderWidget"))
        self.horizontalLayout.addWidget(self.x_SliderWidget)
        self.x_current_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_current_InputWidget.sizePolicy().hasHeightForWidth())
        self.x_current_InputWidget.setSizePolicy(sizePolicy)
        self.x_current_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_current_InputWidget.setMouseTracking(True)
        self.x_current_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.x_current_InputWidget.setAcceptDrops(True)
        self.x_current_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_current_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.x_current_InputWidget.setAccelerated(True)
        self.x_current_InputWidget.setDecimals(3)
        self.x_current_InputWidget.setMinimum(-1000.0)
        self.x_current_InputWidget.setMaximum(1000.0)
        self.x_current_InputWidget.setSingleStep(0.01)
        self.x_current_InputWidget.setObjectName(_fromUtf8("x_current_InputWidget"))
        self.horizontalLayout.addWidget(self.x_current_InputWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem4 = QtGui.QSpacerItem(56, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.line_3 = QtGui.QFrame(self.dockWidgetContents_3)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_3.addWidget(self.line_3)
        self.y_min_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_min_InputWidget.sizePolicy().hasHeightForWidth())
        self.y_min_InputWidget.setSizePolicy(sizePolicy)
        self.y_min_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_min_InputWidget.setMouseTracking(True)
        self.y_min_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.y_min_InputWidget.setAcceptDrops(True)
        self.y_min_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_min_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.y_min_InputWidget.setAccelerated(True)
        self.y_min_InputWidget.setMinimum(-200.0)
        self.y_min_InputWidget.setMaximum(200.0)
        self.y_min_InputWidget.setObjectName(_fromUtf8("y_min_InputWidget"))
        self.horizontalLayout_3.addWidget(self.y_min_InputWidget)
        self.y_max_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_max_InputWidget.sizePolicy().hasHeightForWidth())
        self.y_max_InputWidget.setSizePolicy(sizePolicy)
        self.y_max_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_max_InputWidget.setMouseTracking(True)
        self.y_max_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.y_max_InputWidget.setAcceptDrops(True)
        self.y_max_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_max_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.y_max_InputWidget.setAccelerated(True)
        self.y_max_InputWidget.setMinimum(-200.0)
        self.y_max_InputWidget.setMaximum(200.0)
        self.y_max_InputWidget.setObjectName(_fromUtf8("y_max_InputWidget"))
        self.horizontalLayout_3.addWidget(self.y_max_InputWidget)
        self.y_SliderWidget = QtGui.QSlider(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_SliderWidget.sizePolicy().hasHeightForWidth())
        self.y_SliderWidget.setSizePolicy(sizePolicy)
        self.y_SliderWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.y_SliderWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.y_SliderWidget.setBaseSize(QtCore.QSize(0, 0))
        self.y_SliderWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.y_SliderWidget.setOrientation(QtCore.Qt.Horizontal)
        self.y_SliderWidget.setObjectName(_fromUtf8("y_SliderWidget"))
        self.horizontalLayout_3.addWidget(self.y_SliderWidget)
        self.y_current_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_current_InputWidget.sizePolicy().hasHeightForWidth())
        self.y_current_InputWidget.setSizePolicy(sizePolicy)
        self.y_current_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_current_InputWidget.setMouseTracking(True)
        self.y_current_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.y_current_InputWidget.setAcceptDrops(True)
        self.y_current_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_current_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.y_current_InputWidget.setAccelerated(True)
        self.y_current_InputWidget.setDecimals(3)
        self.y_current_InputWidget.setMinimum(-1000.0)
        self.y_current_InputWidget.setMaximum(1000.0)
        self.y_current_InputWidget.setSingleStep(0.01)
        self.y_current_InputWidget.setObjectName(_fromUtf8("y_current_InputWidget"))
        self.horizontalLayout_3.addWidget(self.y_current_InputWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.z_res_InputWidget = QtGui.QSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_res_InputWidget.sizePolicy().hasHeightForWidth())
        self.z_res_InputWidget.setSizePolicy(sizePolicy)
        self.z_res_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.z_res_InputWidget.setMouseTracking(True)
        self.z_res_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.z_res_InputWidget.setAcceptDrops(True)
        self.z_res_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_res_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.z_res_InputWidget.setAccelerated(True)
        self.z_res_InputWidget.setMaximum(10000)
        self.z_res_InputWidget.setObjectName(_fromUtf8("z_res_InputWidget"))
        self.horizontalLayout_2.addWidget(self.z_res_InputWidget)
        self.line_4 = QtGui.QFrame(self.dockWidgetContents_3)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_2.addWidget(self.line_4)
        self.z_min_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_min_InputWidget.sizePolicy().hasHeightForWidth())
        self.z_min_InputWidget.setSizePolicy(sizePolicy)
        self.z_min_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.z_min_InputWidget.setMouseTracking(True)
        self.z_min_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.z_min_InputWidget.setAcceptDrops(True)
        self.z_min_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_min_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.z_min_InputWidget.setAccelerated(True)
        self.z_min_InputWidget.setMinimum(-200.0)
        self.z_min_InputWidget.setMaximum(200.0)
        self.z_min_InputWidget.setObjectName(_fromUtf8("z_min_InputWidget"))
        self.horizontalLayout_2.addWidget(self.z_min_InputWidget)
        self.z_max_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_max_InputWidget.sizePolicy().hasHeightForWidth())
        self.z_max_InputWidget.setSizePolicy(sizePolicy)
        self.z_max_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.z_max_InputWidget.setMouseTracking(True)
        self.z_max_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.z_max_InputWidget.setAcceptDrops(True)
        self.z_max_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_max_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.z_max_InputWidget.setAccelerated(True)
        self.z_max_InputWidget.setMinimum(-200.0)
        self.z_max_InputWidget.setMaximum(200.0)
        self.z_max_InputWidget.setObjectName(_fromUtf8("z_max_InputWidget"))
        self.horizontalLayout_2.addWidget(self.z_max_InputWidget)
        self.z_SliderWidget = QtGui.QSlider(self.dockWidgetContents_3)
        self.z_SliderWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.z_SliderWidget.setOrientation(QtCore.Qt.Horizontal)
        self.z_SliderWidget.setObjectName(_fromUtf8("z_SliderWidget"))
        self.horizontalLayout_2.addWidget(self.z_SliderWidget)
        self.z_current_InputWidget = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_current_InputWidget.sizePolicy().hasHeightForWidth())
        self.z_current_InputWidget.setSizePolicy(sizePolicy)
        self.z_current_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.z_current_InputWidget.setMouseTracking(True)
        self.z_current_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.z_current_InputWidget.setAcceptDrops(True)
        self.z_current_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_current_InputWidget.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.z_current_InputWidget.setDecimals(3)
        self.z_current_InputWidget.setMinimum(-1000.0)
        self.z_current_InputWidget.setMaximum(1000.0)
        self.z_current_InputWidget.setSingleStep(0.01)
        self.z_current_InputWidget.setObjectName(_fromUtf8("z_current_InputWidget"))
        self.horizontalLayout_2.addWidget(self.z_current_InputWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.scan_control_dockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.scan_control_dockWidget)
        self.xy_scan_dockWidget = QtGui.QDockWidget(MainWindow)
        self.xy_scan_dockWidget.setObjectName(_fromUtf8("xy_scan_dockWidget"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.xy_ViewWidget = PlotWidget(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_ViewWidget.sizePolicy().hasHeightForWidth())
        self.xy_ViewWidget.setSizePolicy(sizePolicy)
        self.xy_ViewWidget.setObjectName(_fromUtf8("xy_ViewWidget"))
        self.horizontalLayout_4.addWidget(self.xy_ViewWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.xy_cb_max_InputWidget = QtGui.QSpinBox(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_cb_max_InputWidget.sizePolicy().hasHeightForWidth())
        self.xy_cb_max_InputWidget.setSizePolicy(sizePolicy)
        self.xy_cb_max_InputWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.xy_cb_max_InputWidget.setMouseTracking(True)
        self.xy_cb_max_InputWidget.setAcceptDrops(True)
        self.xy_cb_max_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xy_cb_max_InputWidget.setAccelerated(True)
        self.xy_cb_max_InputWidget.setMinimum(-100000000)
        self.xy_cb_max_InputWidget.setMaximum(100000000)
        self.xy_cb_max_InputWidget.setSingleStep(1000)
        self.xy_cb_max_InputWidget.setProperty("value", 100000)
        self.xy_cb_max_InputWidget.setObjectName(_fromUtf8("xy_cb_max_InputWidget"))
        self.verticalLayout.addWidget(self.xy_cb_max_InputWidget)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.xy_cb_high_centile_InputWidget = QtGui.QSpinBox(self.dockWidgetContents_4)
        self.xy_cb_high_centile_InputWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.xy_cb_high_centile_InputWidget.setMinimum(0)
        self.xy_cb_high_centile_InputWidget.setMaximum(100)
        self.xy_cb_high_centile_InputWidget.setProperty("value", 100)
        self.xy_cb_high_centile_InputWidget.setObjectName(_fromUtf8("xy_cb_high_centile_InputWidget"))
        self.horizontalLayout_9.addWidget(self.xy_cb_high_centile_InputWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.xy_cb_ViewWidget = PlotWidget(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_cb_ViewWidget.sizePolicy().hasHeightForWidth())
        self.xy_cb_ViewWidget.setSizePolicy(sizePolicy)
        self.xy_cb_ViewWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.xy_cb_ViewWidget.setObjectName(_fromUtf8("xy_cb_ViewWidget"))
        self.verticalLayout.addWidget(self.xy_cb_ViewWidget)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.xy_cb_low_centile_InputWidget = QtGui.QSpinBox(self.dockWidgetContents_4)
        self.xy_cb_low_centile_InputWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.xy_cb_low_centile_InputWidget.setMaximum(100)
        self.xy_cb_low_centile_InputWidget.setProperty("value", 0)
        self.xy_cb_low_centile_InputWidget.setObjectName(_fromUtf8("xy_cb_low_centile_InputWidget"))
        self.horizontalLayout_8.addWidget(self.xy_cb_low_centile_InputWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.xy_cb_min_InputWidget = QtGui.QSpinBox(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_cb_min_InputWidget.sizePolicy().hasHeightForWidth())
        self.xy_cb_min_InputWidget.setSizePolicy(sizePolicy)
        self.xy_cb_min_InputWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.xy_cb_min_InputWidget.setMouseTracking(True)
        self.xy_cb_min_InputWidget.setAcceptDrops(True)
        self.xy_cb_min_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xy_cb_min_InputWidget.setAccelerated(True)
        self.xy_cb_min_InputWidget.setMinimum(-100000000)
        self.xy_cb_min_InputWidget.setMaximum(100000000)
        self.xy_cb_min_InputWidget.setSingleStep(1000)
        self.xy_cb_min_InputWidget.setProperty("value", 100)
        self.xy_cb_min_InputWidget.setObjectName(_fromUtf8("xy_cb_min_InputWidget"))
        self.verticalLayout.addWidget(self.xy_cb_min_InputWidget)
        self.xy_cb_centiles_RadioButton = QtGui.QRadioButton(self.dockWidgetContents_4)
        self.xy_cb_centiles_RadioButton.setChecked(True)
        self.xy_cb_centiles_RadioButton.setObjectName(_fromUtf8("xy_cb_centiles_RadioButton"))
        self.verticalLayout.addWidget(self.xy_cb_centiles_RadioButton)
        self.xy_cb_manual_RadioButton = QtGui.QRadioButton(self.dockWidgetContents_4)
        self.xy_cb_manual_RadioButton.setChecked(False)
        self.xy_cb_manual_RadioButton.setObjectName(_fromUtf8("xy_cb_manual_RadioButton"))
        self.verticalLayout.addWidget(self.xy_cb_manual_RadioButton)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.xy_scan_dockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.xy_scan_dockWidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionSave_XY_Scan = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave_XY_Scan.setIcon(icon)
        self.actionSave_XY_Scan.setObjectName(_fromUtf8("actionSave_XY_Scan"))
        self.actionSave_configuration = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave_configuration.setIcon(icon)
        self.actionSave_configuration.setObjectName(_fromUtf8("actionSave_configuration"))
        self.action_Settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("settings"))
        self.action_Settings.setIcon(icon)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))
        self.actionClose = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("window-close"))
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionSave_Depth_Scan = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave_Depth_Scan.setIcon(icon)
        self.actionSave_Depth_Scan.setObjectName(_fromUtf8("actionSave_Depth_Scan"))
        self.action_optimizer_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("settings"))
        self.action_optimizer_settings.setIcon(icon)
        self.action_optimizer_settings.setObjectName(_fromUtf8("action_optimizer_settings"))
        self.actionSave_XY_Image_Data = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave_XY_Image_Data.setIcon(icon)
        self.actionSave_XY_Image_Data.setObjectName(_fromUtf8("actionSave_XY_Image_Data"))
        self.actionSave_Depth_Image_Data = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave_Depth_Image_Data.setIcon(icon)
        self.actionSave_Depth_Image_Data.setObjectName(_fromUtf8("actionSave_Depth_Image_Data"))
        self.action_zoom = QtGui.QAction(MainWindow)
        self.action_zoom.setCheckable(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("zoom-select"))
        self.action_zoom.setIcon(icon)
        self.action_zoom.setObjectName(_fromUtf8("action_zoom"))
        self.actionXY_scan_view = QtGui.QAction(MainWindow)
        self.actionXY_scan_view.setCheckable(True)
        self.actionXY_scan_view.setChecked(True)
        self.actionXY_scan_view.setObjectName(_fromUtf8("actionXY_scan_view"))
        self.actionDepth_scan_view = QtGui.QAction(MainWindow)
        self.actionDepth_scan_view.setCheckable(True)
        self.actionDepth_scan_view.setChecked(True)
        self.actionDepth_scan_view.setObjectName(_fromUtf8("actionDepth_scan_view"))
        self.actionScan_control_view = QtGui.QAction(MainWindow)
        self.actionScan_control_view.setCheckable(True)
        self.actionScan_control_view.setChecked(True)
        self.actionScan_control_view.setObjectName(_fromUtf8("actionScan_control_view"))
        self.actionOptimizer_view = QtGui.QAction(MainWindow)
        self.actionOptimizer_view.setCheckable(True)
        self.actionOptimizer_view.setChecked(True)
        self.actionOptimizer_view.setObjectName(_fromUtf8("actionOptimizer_view"))
        self.action_scan_xy_start = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("scan_xy_start"))
        self.action_scan_xy_start.setIcon(icon)
        self.action_scan_xy_start.setObjectName(_fromUtf8("action_scan_xy_start"))
        self.action_scan_xy_resume = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("scan_xy_resume"))
        self.action_scan_xy_resume.setIcon(icon)
        self.action_scan_xy_resume.setObjectName(_fromUtf8("action_scan_xy_resume"))
        self.action_scan_depth_start = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("scan_depth_start"))
        self.action_scan_depth_start.setIcon(icon)
        self.action_scan_depth_start.setObjectName(_fromUtf8("action_scan_depth_start"))
        self.action_scan_depth_resume = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("scan_depth_resume"))
        self.action_scan_depth_resume.setIcon(icon)
        self.action_scan_depth_resume.setObjectName(_fromUtf8("action_scan_depth_resume"))
        self.action_optimize_position = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("optimize_position"))
        self.action_optimize_position.setIcon(icon)
        self.action_optimize_position.setObjectName(_fromUtf8("action_optimize_position"))
        self.action_stop_scanning = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("stop_scan"))
        self.action_stop_scanning.setIcon(icon)
        self.action_stop_scanning.setObjectName(_fromUtf8("action_stop_scanning"))
        self.action_loop_scan_xy = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("permanent_scan_xy"))
        self.action_loop_scan_xy.setIcon(icon)
        self.action_loop_scan_xy.setObjectName(_fromUtf8("action_loop_scan_xy"))
        self.action_loop_scan_depth = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("permanent_scan_depth"))
        self.action_loop_scan_depth.setIcon(icon)
        self.action_loop_scan_depth.setObjectName(_fromUtf8("action_loop_scan_depth"))
        self.restore_default_view_Action = QtGui.QAction(MainWindow)
        self.restore_default_view_Action.setObjectName(_fromUtf8("restore_default_view_Action"))
        self.menuFile.addAction(self.actionSave_XY_Scan)
        self.menuFile.addAction(self.actionSave_Depth_Scan)
        self.menuFile.addAction(self.actionSave_XY_Image_Data)
        self.menuFile.addAction(self.actionSave_Depth_Image_Data)
        self.menuFile.addAction(self.actionSave_configuration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menu_Options.addAction(self.action_Settings)
        self.menu_Options.addAction(self.action_optimizer_settings)
        self.menu_Options.addAction(self.action_scan_xy_start)
        self.menuView.addAction(self.actionXY_scan_view)
        self.menuView.addAction(self.actionDepth_scan_view)
        self.menuView.addAction(self.actionScan_control_view)
        self.menuView.addAction(self.actionOptimizer_view)
        self.menuView.addSeparator()
        self.menuView.addAction(self.restore_default_view_Action)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.action_scan_xy_start)
        self.toolBar.addAction(self.action_scan_xy_resume)
        self.toolBar.addAction(self.action_loop_scan_xy)
        self.toolBar.addAction(self.action_stop_scanning)
        self.toolBar.addAction(self.action_scan_depth_start)
        self.toolBar.addAction(self.action_scan_depth_resume)
        self.toolBar.addAction(self.action_loop_scan_depth)
        self.toolBar.addAction(self.action_optimize_position)
        self.toolBar_2.addAction(self.action_zoom)
        self.toolBar_2.addAction(self.action_optimize_position)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionXY_scan_view, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.xy_scan_dockWidget.setVisible)
        QtCore.QObject.connect(self.xy_scan_dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionXY_scan_view.setChecked)
        QtCore.QObject.connect(self.actionDepth_scan_view, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.depth_scan_dockWidget.setVisible)
        QtCore.QObject.connect(self.depth_scan_dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDepth_scan_view.setChecked)
        QtCore.QObject.connect(self.actionScan_control_view, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.scan_control_dockWidget.setVisible)
        QtCore.QObject.connect(self.scan_control_dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionScan_control_view.setChecked)
        QtCore.QObject.connect(self.actionOptimizer_view, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.optimizer_dockWidget.setVisible)
        QtCore.QObject.connect(self.optimizer_dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionOptimizer_view.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.xy_res_InputWidget, self.z_res_InputWidget)
        MainWindow.setTabOrder(self.z_res_InputWidget, self.x_min_InputWidget)
        MainWindow.setTabOrder(self.x_min_InputWidget, self.x_max_InputWidget)
        MainWindow.setTabOrder(self.x_max_InputWidget, self.y_min_InputWidget)
        MainWindow.setTabOrder(self.y_min_InputWidget, self.y_max_InputWidget)
        MainWindow.setTabOrder(self.y_max_InputWidget, self.z_min_InputWidget)
        MainWindow.setTabOrder(self.z_min_InputWidget, self.z_max_InputWidget)
        MainWindow.setTabOrder(self.z_max_InputWidget, self.x_current_InputWidget)
        MainWindow.setTabOrder(self.x_current_InputWidget, self.y_current_InputWidget)
        MainWindow.setTabOrder(self.y_current_InputWidget, self.z_current_InputWidget)
        MainWindow.setTabOrder(self.z_current_InputWidget, self.z_SliderWidget)
        MainWindow.setTabOrder(self.z_SliderWidget, self.y_SliderWidget)
        MainWindow.setTabOrder(self.y_SliderWidget, self.x_SliderWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qudi: Confocal", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Options.setTitle(_translate("MainWindow", "&Options", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.depth_scan_dockWidget.setWindowTitle(_translate("MainWindow", "Depth scan", None))
        self.label_12.setText(_translate("MainWindow", "%", None))
        self.label_8.setText(_translate("MainWindow", "%", None))
        self.depth_cb_centiles_RadioButton.setText(_translate("MainWindow", "Centiles", None))
        self.depth_cb_manual_RadioButton.setText(_translate("MainWindow", "Manual", None))
        self.optimizer_dockWidget.setWindowTitle(_translate("MainWindow", "Optimizer", None))
        self.label_9.setText(_translate("MainWindow", "(x,y,z): ", None))
        self.refocus_position_label.setToolTip(_translate("MainWindow", "This text is selectable.  Copy and paste into labnotes.", None))
        self.refocus_position_label.setText(_translate("MainWindow", "(?, ?, ?)", None))
        self.scan_control_dockWidget.setWindowTitle(_translate("MainWindow", "Scan control", None))
        self.label_4.setText(_translate("MainWindow", "Resolution", None))
        self.label_5.setText(_translate("MainWindow", "Scan Range", None))
        self.label.setText(_translate("MainWindow", "X-Axis :", None))
        self.xy_res_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">XY-Resolution</span></p></body></html>", None))
        self.x_min_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X_Min</span></p></body></html>", None))
        self.x_max_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X_Max</span></p></body></html>", None))
        self.x_current_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X-position</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Y-Axis :", None))
        self.y_min_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y_Min</span></p></body></html>", None))
        self.y_max_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y_Max</span></p></body></html>", None))
        self.y_current_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y-position</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "Z-Axis :", None))
        self.z_res_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z-Resolution</span></p></body></html>", None))
        self.z_min_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z_Min</span></p></body></html>", None))
        self.z_max_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z_Max</span></p></body></html>", None))
        self.z_current_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z-position</span></p></body></html>", None))
        self.xy_scan_dockWidget.setWindowTitle(_translate("MainWindow", "XY scan", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">%</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">%</p></body></html>", None))
        self.xy_cb_centiles_RadioButton.setText(_translate("MainWindow", "Centiles", None))
        self.xy_cb_manual_RadioButton.setText(_translate("MainWindow", "Manual", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Scaning toolbar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.actionSave_XY_Scan.setText(_translate("MainWindow", "Save XY Data", None))
        self.actionSave_configuration.setText(_translate("MainWindow", "Save &configuration", None))
        self.action_Settings.setText(_translate("MainWindow", "&Settings", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setToolTip(_translate("MainWindow", "Close confocal", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.actionSave_Depth_Scan.setText(_translate("MainWindow", "Save XZ Data", None))
        self.action_optimizer_settings.setText(_translate("MainWindow", "Optimizer Settings", None))
        self.actionSave_XY_Image_Data.setText(_translate("MainWindow", "Save XY Image+Data", None))
        self.actionSave_Depth_Image_Data.setText(_translate("MainWindow", "Save XZ Image+Data", None))
        self.action_zoom.setText(_translate("MainWindow", "zoom", None))
        self.actionXY_scan_view.setText(_translate("MainWindow", "XY scan", None))
        self.actionXY_scan_view.setShortcut(_translate("MainWindow", "Alt+X", None))
        self.actionDepth_scan_view.setText(_translate("MainWindow", "Depth scan", None))
        self.actionDepth_scan_view.setShortcut(_translate("MainWindow", "Alt+D", None))
        self.actionScan_control_view.setText(_translate("MainWindow", "Scan control", None))
        self.actionScan_control_view.setShortcut(_translate("MainWindow", "Alt+C", None))
        self.actionOptimizer_view.setText(_translate("MainWindow", "Optimizer", None))
        self.actionOptimizer_view.setShortcut(_translate("MainWindow", "Alt+O", None))
        self.action_scan_xy_start.setText(_translate("MainWindow", "Scan XY", None))
        self.action_scan_xy_start.setToolTip(_translate("MainWindow", "Start a fresh XY scan", None))
        self.action_scan_xy_resume.setText(_translate("MainWindow", "Resume XY scan", None))
        self.action_scan_xy_resume.setToolTip(_translate("MainWindow", "Resume an interrupted XY scan", None))
        self.action_scan_depth_start.setText(_translate("MainWindow", "Scan depth", None))
        self.action_scan_depth_start.setToolTip(_translate("MainWindow", "Start a fresh depth scan", None))
        self.action_scan_depth_resume.setText(_translate("MainWindow", "Resume depth scan", None))
        self.action_scan_depth_resume.setToolTip(_translate("MainWindow", "Resume an interrupted depth scan", None))
        self.action_optimize_position.setText(_translate("MainWindow", "Optimize position", None))
        self.action_optimize_position.setToolTip(_translate("MainWindow", "Optimize position of crosshair", None))
        self.action_stop_scanning.setText(_translate("MainWindow", "Stop scan", None))
        self.action_stop_scanning.setToolTip(_translate("MainWindow", "Stop scanning XY or depth and return to \"ready\" state", None))
        self.action_loop_scan_xy.setText(_translate("MainWindow", "Loop Scan XY", None))
        self.action_loop_scan_xy.setToolTip(_translate("MainWindow", "Start a permanent XY Scan", None))
        self.action_loop_scan_depth.setText(_translate("MainWindow", "Loop Scan Depth", None))
        self.action_loop_scan_depth.setToolTip(_translate("MainWindow", "Start a permanent depth scan", None))
        self.restore_default_view_Action.setText(_translate("MainWindow", "Restore default", None))
        self.restore_default_view_Action.setToolTip(_translate("MainWindow", "Restore default arrangement of dock widgets ", None))

from pyqtgraph import PlotWidget
