# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PulsedMeasurementGuiUI.ui'
#
# Created: Wed May 20 12:07:14 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(974, 871)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.measurement_tab = QtGui.QWidget()
        self.measurement_tab.setObjectName(_fromUtf8("measurement_tab"))
        self.lasertrace_plot_ViewWidget = PlotWidget(self.measurement_tab)
        self.lasertrace_plot_ViewWidget.setGeometry(QtCore.QRect(10, 490, 931, 290))
        self.lasertrace_plot_ViewWidget.setAutoFillBackground(False)
        self.lasertrace_plot_ViewWidget.setObjectName(_fromUtf8("lasertrace_plot_ViewWidget"))
        self.lasertrace_plot_ViewWidget_2 = PlotWidget(self.measurement_tab)
        self.lasertrace_plot_ViewWidget_2.setGeometry(QtCore.QRect(10, 190, 931, 290))
        self.lasertrace_plot_ViewWidget_2.setAutoFillBackground(False)
        self.lasertrace_plot_ViewWidget_2.setObjectName(_fromUtf8("lasertrace_plot_ViewWidget_2"))
        self.gridLayoutWidget = QtGui.QWidget(self.measurement_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 931, 161))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frequency_InputWidget_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.frequency_InputWidget_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.frequency_InputWidget_2.setObjectName(_fromUtf8("frequency_InputWidget_2"))
        self.gridLayout_3.addWidget(self.frequency_InputWidget_2, 2, 1, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_3.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.power_InputWidget_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.power_InputWidget_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.power_InputWidget_2.setObjectName(_fromUtf8("power_InputWidget_2"))
        self.gridLayout_3.addWidget(self.power_InputWidget_2, 3, 1, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_3.addWidget(self.radioButton, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_3.addWidget(self.comboBox, 1, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 3, 1, 1)
        self.tabWidget.addTab(self.measurement_tab, _fromUtf8(""))
        self.sequence_tab = QtGui.QWidget()
        self.sequence_tab.setObjectName(_fromUtf8("sequence_tab"))
        self.tableWidget = QtGui.QTableWidget(self.sequence_tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 160, 931, 611))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(27)
        self.tabWidget.addTab(self.sequence_tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Settings = QtGui.QAction(MainWindow)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qudi: pulsed measurement", None))
        self.radioButton_2.setText(_translate("MainWindow", "Run", None))
        self.label_11.setText(_translate("MainWindow", "Frequency [MHz] :", None))
        self.radioButton.setText(_translate("MainWindow", "Idle", None))
        self.label_12.setText(_translate("MainWindow", "Power [dBm] :", None))
        self.label_10.setText(_translate("MainWindow", "Fast counter binning [ns] :", None))
        self.label_9.setText(_translate("MainWindow", "Pulse sequence to run :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.measurement_tab), _translate("MainWindow", "measurement", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Neue Zeile", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Chnl 0", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Chnl 1", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Chnl 2", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Chnl 3", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Chnl 4", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Chnl 5", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Chnl 6", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Chnl 7", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Duration [bins]", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Use as tau?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sequence_tab), _translate("MainWindow", "sequence", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.action_Settings.setText(_translate("MainWindow", "&Settings", None))

from pyqtgraph import PlotWidget
