# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PulsedMeasurementGuiUI.ui'
#
# Created: Fri May 29 13:46:40 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(974, 871)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.measurement_tab = QtGui.QWidget()
        self.measurement_tab.setObjectName(_fromUtf8("measurement_tab"))
        self.lasertrace_plot_ViewWidget = PlotWidget(self.measurement_tab)
        self.lasertrace_plot_ViewWidget.setGeometry(QtCore.QRect(10, 490, 931, 290))
        self.lasertrace_plot_ViewWidget.setAutoFillBackground(False)
        self.lasertrace_plot_ViewWidget.setObjectName(_fromUtf8("lasertrace_plot_ViewWidget"))
        self.signal_plot_ViewWidget = PlotWidget(self.measurement_tab)
        self.signal_plot_ViewWidget.setGeometry(QtCore.QRect(10, 190, 931, 290))
        self.signal_plot_ViewWidget.setAutoFillBackground(False)
        self.signal_plot_ViewWidget.setObjectName(_fromUtf8("signal_plot_ViewWidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.measurement_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 931, 161))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 2)
        self.binning_comboBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.binning_comboBox.setObjectName(_fromUtf8("binning_comboBox"))
        self.gridLayout_3.addWidget(self.binning_comboBox, 1, 2, 1, 1)
        self.power_InputWidget = QtGui.QLineEdit(self.gridLayoutWidget)
        self.power_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.power_InputWidget.setObjectName(_fromUtf8("power_InputWidget"))
        self.gridLayout_3.addWidget(self.power_InputWidget, 3, 2, 1, 1)
        self.run_radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.run_radioButton.setObjectName(_fromUtf8("run_radioButton"))
        self.gridLayout_3.addWidget(self.run_radioButton, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 2)
        self.idle_radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.idle_radioButton.setObjectName(_fromUtf8("idle_radioButton"))
        self.gridLayout_3.addWidget(self.idle_radioButton, 0, 0, 1, 1)
        self.frequency_InputWidget = QtGui.QLineEdit(self.gridLayoutWidget)
        self.frequency_InputWidget.setMaximumSize(QtCore.QSize(75, 16777215))
        self.frequency_InputWidget.setObjectName(_fromUtf8("frequency_InputWidget"))
        self.gridLayout_3.addWidget(self.frequency_InputWidget, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 2)
        self.sequence_name_comboBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.sequence_name_comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.sequence_name_comboBox.setObjectName(_fromUtf8("sequence_name_comboBox"))
        self.gridLayout_3.addWidget(self.sequence_name_comboBox, 1, 5, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 3, 1, 1)
        self.tabWidget.addTab(self.measurement_tab, _fromUtf8(""))
        self.sequence_tab = QtGui.QWidget()
        self.sequence_tab.setObjectName(_fromUtf8("sequence_tab"))
        self.sequence_tableWidget = QtGui.QTableWidget(self.sequence_tab)
        self.sequence_tableWidget.setGeometry(QtCore.QRect(10, 140, 931, 611))
        self.sequence_tableWidget.setAlternatingRowColors(False)
        self.sequence_tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.sequence_tableWidget.setWordWrap(True)
        self.sequence_tableWidget.setObjectName(_fromUtf8("sequence_tableWidget"))
        self.sequence_tableWidget.setColumnCount(12)
        self.sequence_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(11, item)
        self.sequence_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.sequence_tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.sequence_tableWidget.horizontalHeader().setStretchLastSection(False)
        self.addrow_pushButton = QtGui.QPushButton(self.sequence_tab)
        self.addrow_pushButton.setGeometry(QtCore.QRect(100, 90, 31, 31))
        self.addrow_pushButton.setObjectName(_fromUtf8("addrow_pushButton"))
        self.deleterow_pushButton = QtGui.QPushButton(self.sequence_tab)
        self.deleterow_pushButton.setGeometry(QtCore.QRect(140, 90, 31, 31))
        self.deleterow_pushButton.setObjectName(_fromUtf8("deleterow_pushButton"))
        self.save_sequence_pushButton = QtGui.QPushButton(self.sequence_tab)
        self.save_sequence_pushButton.setGeometry(QtCore.QRect(270, 60, 111, 21))
        self.save_sequence_pushButton.setObjectName(_fromUtf8("save_sequence_pushButton"))
        self.sequence_name_lineEdit = QtGui.QLineEdit(self.sequence_tab)
        self.sequence_name_lineEdit.setGeometry(QtCore.QRect(100, 60, 161, 21))
        self.sequence_name_lineEdit.setObjectName(_fromUtf8("sequence_name_lineEdit"))
        self.label = QtGui.QLabel(self.sequence_tab)
        self.label.setGeometry(QtCore.QRect(10, 60, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.sequence_list_comboBox = QtGui.QComboBox(self.sequence_tab)
        self.sequence_list_comboBox.setGeometry(QtCore.QRect(100, 20, 161, 22))
        self.sequence_list_comboBox.setObjectName(_fromUtf8("sequence_list_comboBox"))
        self.label_2 = QtGui.QLabel(self.sequence_tab)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.sequence_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 81, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.length_s_lcdNumber = QtGui.QLCDNumber(self.sequence_tab)
        self.length_s_lcdNumber.setGeometry(QtCore.QRect(590, 70, 101, 23))
        self.length_s_lcdNumber.setAutoFillBackground(False)
        self.length_s_lcdNumber.setSmallDecimalPoint(False)
        self.length_s_lcdNumber.setDigitCount(5)
        self.length_s_lcdNumber.setProperty("value", 0.0)
        self.length_s_lcdNumber.setObjectName(_fromUtf8("length_s_lcdNumber"))
        self.line = QtGui.QFrame(self.sequence_tab)
        self.line.setGeometry(QtCore.QRect(380, 10, 20, 121))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_4 = QtGui.QLabel(self.sequence_tab)
        self.label_4.setGeometry(QtCore.QRect(460, 40, 121, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.sequence_tab)
        self.label_5.setGeometry(QtCore.QRect(460, 70, 121, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.sequence_tab)
        self.label_6.setGeometry(QtCore.QRect(410, 10, 171, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.length_bins_lcdNumber = QtGui.QLCDNumber(self.sequence_tab)
        self.length_bins_lcdNumber.setGeometry(QtCore.QRect(590, 40, 101, 23))
        self.length_bins_lcdNumber.setNumDigits(10)
        self.length_bins_lcdNumber.setProperty("intValue", 0)
        self.length_bins_lcdNumber.setObjectName(_fromUtf8("length_bins_lcdNumber"))
        self.pg_frequency_lineEdit = QtGui.QLineEdit(self.sequence_tab)
        self.pg_frequency_lineEdit.setGeometry(QtCore.QRect(590, 10, 101, 21))
        self.pg_frequency_lineEdit.setObjectName(_fromUtf8("pg_frequency_lineEdit"))
        self.label_7 = QtGui.QLabel(self.sequence_tab)
        self.label_7.setGeometry(QtCore.QRect(460, 100, 121, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.size_MB_lcdNumber = QtGui.QLCDNumber(self.sequence_tab)
        self.size_MB_lcdNumber.setGeometry(QtCore.QRect(590, 100, 101, 23))
        self.size_MB_lcdNumber.setObjectName(_fromUtf8("size_MB_lcdNumber"))
        self.clear_list_pushButton = QtGui.QPushButton(self.sequence_tab)
        self.clear_list_pushButton.setGeometry(QtCore.QRect(180, 100, 81, 21))
        self.clear_list_pushButton.setObjectName(_fromUtf8("clear_list_pushButton"))
        self.delete_sequence_pushButton = QtGui.QPushButton(self.sequence_tab)
        self.delete_sequence_pushButton.setGeometry(QtCore.QRect(270, 20, 111, 21))
        self.delete_sequence_pushButton.setObjectName(_fromUtf8("delete_sequence_pushButton"))
        self.label_8 = QtGui.QLabel(self.sequence_tab)
        self.label_8.setGeometry(QtCore.QRect(710, 10, 121, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.laser_number_lcdNumber = QtGui.QLCDNumber(self.sequence_tab)
        self.laser_number_lcdNumber.setGeometry(QtCore.QRect(840, 10, 101, 23))
        self.laser_number_lcdNumber.setObjectName(_fromUtf8("laser_number_lcdNumber"))
        self.label_13 = QtGui.QLabel(self.sequence_tab)
        self.label_13.setGeometry(QtCore.QRect(710, 760, 121, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.repetitions_lineEdit = QtGui.QLineEdit(self.sequence_tab)
        self.repetitions_lineEdit.setGeometry(QtCore.QRect(840, 760, 101, 21))
        self.repetitions_lineEdit.setObjectName(_fromUtf8("repetitions_lineEdit"))
        self.tabWidget.addTab(self.sequence_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qudi: pulsed measurement", None))
        self.label_12.setText(_translate("MainWindow", "MW Power [dBm] :", None))
        self.run_radioButton.setText(_translate("MainWindow", "Run", None))
        self.label_11.setText(_translate("MainWindow", "MW Frequency [MHz] :", None))
        self.idle_radioButton.setText(_translate("MainWindow", "Idle", None))
        self.label_10.setText(_translate("MainWindow", "Fast counter binning [ns] :", None))
        self.label_9.setText(_translate("MainWindow", "Pulse sequence to run :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.measurement_tab), _translate("MainWindow", "measurement", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ch 0", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ch 1", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ch 2", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ch 3", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ch 4", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ch 5", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ch 6", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ch 7", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Length [bins]", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Increment [bins]", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Repeat?", None))
        item = self.sequence_tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Use as tau?", None))
        self.addrow_pushButton.setText(_translate("MainWindow", "+", None))
        self.deleterow_pushButton.setText(_translate("MainWindow", "-", None))
        self.save_sequence_pushButton.setText(_translate("MainWindow", "Save sequence", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Sequence name :</p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Sequences :</p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Add/Delete row :</p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Sequence length [bins] :</p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Sequence length [ms] :</p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Pulse generator frequency [MHz] :</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Sequence size [MB] :</p></body></html>", None))
        self.clear_list_pushButton.setText(_translate("MainWindow", "Clear list", None))
        self.delete_sequence_pushButton.setText(_translate("MainWindow", "Delete sequence", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Number of laser pulses :</p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Number of repetitions :</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sequence_tab), _translate("MainWindow", "block generation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "sequence editor", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))

from pyqtgraph import PlotWidget
