# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagerWindowUI.ui'
#
# Created: Wed Jun 24 11:45:50 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(466, 609)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.loadAllButton = QtGui.QPushButton(self.centralwidget)
        self.loadAllButton.setObjectName(_fromUtf8("loadAllButton"))
        self.gridLayout.addWidget(self.loadAllButton, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.gridLayout1 = QtGui.QGridLayout(self.tabWidgetPage1)
        self.gridLayout1.setObjectName(_fromUtf8("gridLayout1"))
        self.scrollArea = QtGui.QScrollArea(self.tabWidgetPage1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.guiscroll = QtGui.QWidget()
        self.guiscroll.setGeometry(QtCore.QRect(0, 0, 436, 377))
        self.guiscroll.setObjectName(_fromUtf8("guiscroll"))
        self.scrollArea.setWidget(self.guiscroll)
        self.gridLayout1.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.gridLayout2 = QtGui.QGridLayout(self.tabWidgetPage2)
        self.gridLayout2.setObjectName(_fromUtf8("gridLayout2"))
        self.scrollArea1 = QtGui.QScrollArea(self.tabWidgetPage2)
        self.scrollArea1.setWidgetResizable(True)
        self.scrollArea1.setObjectName(_fromUtf8("scrollArea1"))
        self.logicscroll = QtGui.QWidget()
        self.logicscroll.setGeometry(QtCore.QRect(0, 0, 471, 377))
        self.logicscroll.setObjectName(_fromUtf8("logicscroll"))
        self.scrollArea1.setWidget(self.logicscroll)
        self.gridLayout2.addWidget(self.scrollArea1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.tabWidgetPage3 = QtGui.QWidget()
        self.tabWidgetPage3.setObjectName(_fromUtf8("tabWidgetPage3"))
        self.gridLayout3 = QtGui.QGridLayout(self.tabWidgetPage3)
        self.gridLayout3.setObjectName(_fromUtf8("gridLayout3"))
        self.scrollArea2 = QtGui.QScrollArea(self.tabWidgetPage3)
        self.scrollArea2.setWidgetResizable(True)
        self.scrollArea2.setObjectName(_fromUtf8("scrollArea2"))
        self.hwscroll = QtGui.QWidget()
        self.hwscroll.setGeometry(QtCore.QRect(0, 0, 471, 377))
        self.hwscroll.setObjectName(_fromUtf8("hwscroll"))
        self.scrollArea2.setWidget(self.hwscroll)
        self.gridLayout3.addWidget(self.scrollArea2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 466, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuUtilities = QtGui.QMenu(self.menubar)
        self.menuUtilities.setObjectName(_fromUtf8("menuUtilities"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.config_display_dockWidget = QtGui.QDockWidget(MainWindow)
        self.config_display_dockWidget.setObjectName(_fromUtf8("config_display_dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.treeWidget)
        self.config_display_dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.config_display_dockWidget)
        self.actionLoad_configuration = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.actionLoad_configuration.setIcon(icon)
        self.actionLoad_configuration.setObjectName(_fromUtf8("actionLoad_configuration"))
        self.actionSave_configuration = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave_configuration.setIcon(icon)
        self.actionSave_configuration.setObjectName(_fromUtf8("actionSave_configuration"))
        self.action_Load_all_modules = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.action_Load_all_modules.setIcon(icon)
        self.action_Load_all_modules.setObjectName(_fromUtf8("action_Load_all_modules"))
        self.actionStart_all_modules = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.actionStart_all_modules.setIcon(icon)
        self.actionStart_all_modules.setObjectName(_fromUtf8("actionStart_all_modules"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionLog = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("dialog-warning"))
        self.actionLog.setIcon(icon)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionConsole = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("utilities-terminal"))
        self.actionConsole.setIcon(icon)
        self.actionConsole.setObjectName(_fromUtf8("actionConsole"))
        self.actionAbout_QuDi = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-about"))
        self.actionAbout_QuDi.setIcon(icon)
        self.actionAbout_QuDi.setObjectName(_fromUtf8("actionAbout_QuDi"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.actionAbout_Qt1 = QtGui.QAction(MainWindow)
        self.actionAbout_Qt1.setObjectName(_fromUtf8("actionAbout_Qt1"))
        self.menuMenu.addAction(self.actionLoad_configuration)
        self.menuMenu.addAction(self.actionSave_configuration)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.action_Load_all_modules)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionQuit)
        self.menuUtilities.addAction(self.actionLog)
        self.menuUtilities.addAction(self.actionConsole)
        self.menuAbout.addAction(self.actionAbout_QuDi)
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuUtilities.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qudi: Manager", None))
        self.loadAllButton.setText(_translate("MainWindow", "Load all modules", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "GUI", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "Logic", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("MainWindow", "Hardware", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuUtilities.setTitle(_translate("MainWindow", "Utilities", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.config_display_dockWidget.setWindowTitle(_translate("MainWindow", "Configuration", None))
        self.actionLoad_configuration.setText(_translate("MainWindow", "Load configuration", None))
        self.actionSave_configuration.setText(_translate("MainWindow", "Save configuration", None))
        self.action_Load_all_modules.setText(_translate("MainWindow", " Load all modules", None))
        self.actionStart_all_modules.setText(_translate("MainWindow", "Start all modules", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionLog.setText(_translate("MainWindow", "Log", None))
        self.actionConsole.setText(_translate("MainWindow", "Console", None))
        self.actionAbout_QuDi.setText(_translate("MainWindow", "About QuDi", None))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt", None))
        self.actionAbout_Qt1.setText(_translate("MainWindow", "About Qt", None))

