hist:
  channel: 1
  trigger_channel: 5
  bins_width: 1000
  numer_of_bins: 1000

corr:
  channel_start: 1
  channel_stop: 2
  bins_width: 1000
  numer_of_bins: 1000
ctrate:
  channels: [1,2]

counter:
  channels: [1,2]
  bins_width: 1000000
  n_values: 1000

test_channels: []

channels_params:
  6: # cwave internal scanner
    delay: 0
    trigger_level: 3

currentChan: 1
dumpDir: /fastdata/measurements
maxDumps: 1000000000
maxStream: 1000000000
