hist:
    channel: 1
    trigger_channel: 5
    bins_width: 1000
    number_of_bins: 1000
corr:
    channel_start: 1
    channel_stop: 2
    bins_width: 1000
    number_of_bins: 1000
    channels: [1,2]
counter:
    channels: [1,2]
    bins_width: 1000000
    n_values: 1000
delay:
    1: 0
    2: 0
    3: 0
    4: 0
save_dir:
    dump: ""