/* HHLib Ver. 3.0.0.2     March 2019 */

#define HH_ERROR_NONE						   0 
									
#define HH_ERROR_DEVICE_OPEN_FAIL			  -1 
#define HH_ERROR_DEVICE_BUSY				  -2 
#define HH_ERROR_DEVICE_HEVENT_FAIL			  -3 
#define HH_ERROR_DEVICE_CALLBSET_FAIL		  -4 
#define HH_ERROR_DEVICE_BARMAP_FAIL			  -5 
#define HH_ERROR_DEVICE_CLOSE_FAIL			  -6 
#define HH_ERROR_DEVICE_RESET_FAIL			  -7 
#define HH_ERROR_DEVICE_GETVERSION_FAIL		  -8 
#define HH_ERROR_DEVICE_VERSION_MISMATCH	  -9 
#define HH_ERROR_DEVICE_NOT_OPEN			 -10
									
#define HH_ERROR_INSTANCE_RUNNING			 -16 
#define HH_ERROR_INVALID_ARGUMENT			 -17 
#define HH_ERROR_INVALID_MODE				 -18 
#define HH_ERROR_INVALID_OPTION				 -19 
#define HH_ERROR_INVALID_MEMORY				 -20 
#define HH_ERROR_INVALID_RDATA				 -21 
#define HH_ERROR_NOT_INITIALIZED			 -22 
#define HH_ERROR_NOT_CALIBRATED				 -23 
#define HH_ERROR_DMA_FAIL					 -24 
#define HH_ERROR_XTDEVICE_FAIL				 -25 
#define HH_ERROR_FPGACONF_FAIL				 -26 
#define HH_ERROR_IFCONF_FAIL				 -27 
#define HH_ERROR_FIFORESET_FAIL				 -28 
									
#define HH_ERROR_USB_GETDRIVERVER_FAIL		 -32 
#define HH_ERROR_USB_DRIVERVER_MISMATCH		 -33 
#define HH_ERROR_USB_GETIFINFO_FAIL			 -34 
#define HH_ERROR_USB_HISPEED_FAIL			 -35 
#define HH_ERROR_USB_VCMD_FAIL				 -36 
#define HH_ERROR_USB_BULKRD_FAIL			 -37 
#define HH_ERROR_USB_RESET_FAIL				 -38 

#define HH_ERROR_LANEUP_TIMEOUT				 -40 
#define HH_ERROR_DONEALL_TIMEOUT			 -41 
#define HH_ERROR_MODACK_TIMEOUT				 -42 
#define HH_ERROR_MACTIVE_TIMEOUT			 -43 
#define HH_ERROR_MEMCLEAR_FAIL				 -44 
#define HH_ERROR_MEMTEST_FAIL				 -45 
#define HH_ERROR_CALIB_FAIL					 -46 
#define HH_ERROR_REFSEL_FAIL				 -47 
#define HH_ERROR_STATUS_FAIL				 -48 	
#define HH_ERROR_MODNUM_FAIL				 -49 
#define HH_ERROR_DIGMUX_FAIL				 -50 			
#define HH_ERROR_MODMUX_FAIL				 -51 
#define HH_ERROR_MODFWPCB_MISMATCH			 -52 	
#define HH_ERROR_MODFWVER_MISMATCH			 -53 
#define HH_ERROR_MODPROPERTY_MISMATCH		 -54 	
#define HH_ERROR_INVALID_MAGIC				 -55  
#define HH_ERROR_INVALID_LENGTH				 -56  			
#define HH_ERROR_RATE_FAIL					 -57  	
#define HH_ERROR_MODFWVER_TOO_LOW			 -58
#define HH_ERROR_MODFWVER_TOO_HIGH			 -59

#define HH_ERROR_EEPROM_F01					 -64 
#define HH_ERROR_EEPROM_F02					 -65 
#define HH_ERROR_EEPROM_F03					 -66 
#define HH_ERROR_EEPROM_F04					 -67 
#define HH_ERROR_EEPROM_F05					 -68 
#define HH_ERROR_EEPROM_F06					 -69 
#define HH_ERROR_EEPROM_F07					 -70 
#define HH_ERROR_EEPROM_F08					 -71 
#define HH_ERROR_EEPROM_F09					 -72 
#define HH_ERROR_EEPROM_F10					 -73 
#define HH_ERROR_EEPROM_F11					 -74 

