name: qudi
dependencies:
- backports_abc=0.4=py34_0
- comtypes=1.1.2=py34_0
- cycler=0.10.0=py34_0
- decorator=4.0.4=py34_0
- h5py=2.6.0=np111py34_2
- hdf5=1.8.15.1=vc10_4
- ipykernel=4.5.0=py34_0
- ipython=4.0.1=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=5.2.2=py34_0
- jedi=0.9.0=py34_0
- jinja2=2.8=py34_0
- jpeg=8d=vc10_0
- jsonschema=2.4.0=py34_0
- jupyter=1.0.0=py34_3
- jupyter_client=4.4.0=py34_0
- jupyter_console=5.0.0=py34_0
- jupyter_core=4.2.0=py34_0
- libpng=1.6.17=vc10_1
- libtiff=4.0.6=vc10_1
- lxml=3.5.0=py34_0
- markupsafe=0.23=py34_0
- matplotlib=1.5.1=np111py34_0
- mistune=0.7.1=py34_0
- mkl=11.3.3=1
- msvc_runtime=1.0.1=vc10_0
- nbconvert=4.2.0=py34_0
- nbformat=4.1.0=py34_0
- notebook=4.2.3=py34_0
- numpy=1.11.2=py34_0
- openssl=1.0.2j=vc10_0
- path.py=8.1.2=py34_1
- pickleshare=0.5=py34_0
- pip=8.0.2=py34_0
- pygments=2.0.2=py34_0
- pyparsing=2.1.1=py34_0
- pyqt=4.11.4=py34_7
- pyreadline=2.1=py34_0
- python=3.4.5=0
- python-dateutil=2.5.2=py34_0
- pytz=2016.3=py34_0
- pywin32=219=py34_2
- pyzmq=15.1.0=py34_0
- qt=4.8.7=vc10_8
- qtconsole=4.1.1=py34_1
- qtpy=1.1.2=py34_0
- scipy=0.18.1=np111py34_0
- setuptools=19.6.2=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.18=py34_0
- six=1.10.0=py34_0
- tk=8.5.18=vc10_0
- tornado=4.3=py34_0
- traitlets=4.3.1=py34_0
- vs2010_runtime=10.00.40219.1=0
- wheel=0.29.0=py34_0
- zlib=1.2.8=vc10_2
- pip:
  - backports-abc==0.4
  - fysom==2.1.2
  - gitdb==0.6.4
  - gitpython==2.0.2
  - hdf5storage==0.1.10
  - lmfit==0.9.5
  - plumbum==1.6.0
  - pydaqmx==1.3.2
  - pyqtgraph==0.10.0
  - pyvisa==1.8
  - pyvisa-py==0.2
  - rpyc==3.3.0
  - ruamel.yaml==0.11.15
  - smmap==0.9.0