name: qudi
channels: !!python/tuple
- defaults
dependencies:
- cycler=0.10.0=py36_0
- dbus=1.10.10=0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- ipykernel=4.5.2=py36_0
- ipython=5.1.0=py36_0
- ipython_genutils=0.1.0=py36_0
- ipywidgets=5.2.2=py36_1
- jbig=2.1=0
- jedi=0.9.0=py36_1
- jinja2=2.9.4=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=4.4.0=py36_0
- jupyter_console=5.0.0=py36_0
- jupyter_core=4.2.1=py36_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- lxml=3.7.2=py36_0
- markupsafe=0.23=py36_2
- matplotlib=2.0.0=np112py36_0
- mistune=0.7.3=py36_0
- mkl=2017.0.1=0
- nbconvert=4.2.0=py36_0
- nbformat=4.2.0=py36_0
- notebook=4.3.1=py36_0
- numpy=1.12.0=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2k=0
- path.py=10.0=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.0.0=py36_1
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.9=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.1.3=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=3
- qtconsole=4.2.1=py36_1
- qtpy=1.2.1=py36_0
- readline=6.2=2
- scipy=0.18.1=np112py36_1
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- tk=8.5.18=0
- tornado=4.4.2=py36_0
- traitlets=4.3.1=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=1.2.6=py36_0
- xz=5.2.2=1
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - fysom==2.1.4
  - gitdb2==2.0.0
  - gitpython==2.1.1
  - hdf5storage==0.1.14
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - lmfit==0.9.5
  - plumbum==1.6.3
  - prompt-toolkit==1.0.9
  - pydaqmx==1.3.2
  - pyflowgraph-qo==0.0.3.1
  - pyqtgraph==0.10.0
  - pyvisa==1.8
  - pyvisa-py==0.2
  - rpyc==3.3.0
  - ruamel.yaml==0.13.14
  - serial==0.0.38
  - smmap2==2.0.1
