name: C:\Anaconda3\envs\qudi
dependencies:
- backports_abc=0.4=py34_0
- decorator=4.0.4=py34_0
- ipykernel=4.1.1=py34_0
- ipython=4.0.1=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=4.1.0=py34_0
- jinja2=2.8=py34_0
- jpeg=8d=vc10_0
- jsonschema=2.4.0=py34_0
- jupyter=1.0.0=py34_1
- jupyter_client=4.1.1=py34_0
- jupyter_console=4.0.3=py34_0
- jupyter_core=4.0.6=py34_0
- libpng=1.6.17=vc10_1
- libtiff=4.0.6=vc10_1
- markupsafe=0.23=py34_0
- mistune=0.7.1=py34_0
- msvc_runtime=1.0.1=vc10_0
- nbconvert=4.1.0=py34_0
- nbformat=4.0.1=py34_0
- notebook=4.0.6=py34_0
- numpy=1.10.1=py34_0
- openssl=1.0.2d=vc10_0
- path.py=8.1.2=py34_1
- pickleshare=0.5=py34_0
- pip=7.1.2=py34_0
- pygments=2.0.2=py34_0
- pyqt=4.10.4=py34_1
- pyreadline=2.1=py34_0
- python=3.4.3=5
- pyzmq=15.1.0=py34_0
- qt=4.8.7=vc10_5
- qtconsole=4.1.1=py34_0
- scipy=0.16.0=np110py34_0
- setuptools=19.1.1=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_2
- tornado=4.3=py34_0
- traitlets=4.0.0=py34_0
- wheel=0.26.0=py34_1
- zlib=1.2.8=vc10_2
- pip:
  - backports-abc==0.4
  - fysom==2.1.2
  - hdf5storage==0.1.10
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - lmfit==0.9.2
  - plumbum==1.6.0
  - pydaqmx==1.3.2
  - pyqtgraph==0.9.10
  - python-dateutil==2.2
  - pyvisa==1.8
  - pyvisa-py==0.2
  - rpyc==3.3.0
  - six==1.7.2
  - svn==0.3.36

